### ISSUE TITLE
Apple Search Ads delay

### ISSUE THREAD

**Issue by rongboyang** [BranchMetrics/ios-branch-deep-linking-attribution#1002]
We are trying to add the Apple Search Ads check function. The document says it will add delay to the first time startup, is that accurate?

```objective-c
/**
 Check for Apple Search Ads before initialization.
 
 This will usually add less than 1 second on first time startup.  Up to 3.5 seconds if Apple Search Ads fails to respond.
 */
- (void)delayInitToCheckForSearchAds;

/**
 Increases the amount of time the SDK waits for Apple Search Ads to respond.
 The default wait has a better than 90% success rate, however waiting longer can improve the success rate.

 This will increase the usual delay to about 3 seconds on first time startup.  Up to about 15 seconds if Apple Search Ads fails to respond.
 */
- (void)useLongerWaitForAppleSearchAds;
``` 

```objective-c
- (void)checkAppleSearchAdsAttribution {
    if (![BNCAppleSearchAds sharedInstance].enableAppleSearchAdsCheck) {
        return;
    }
    
    dispatch_async(self.isolationQueue, ^(){
        dispatch_semaphore_t semaphore = dispatch_semaphore_create(0);
        [[BNCAppleSearchAds sharedInstance] checkAppleSearchAdsSaveTo:[BNCPreferenceHelper preferenceHelper] installDate:[BNCApplication currentApplication].currentInstallDate completion:^{
            dispatch_semaphore_signal(semaphore);
        }];
        dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);
    });
}
```

When looking at what `delayInitToCheckForSearchAds` does, it only sets a flag on the BNCAppleSearchAds's sharedInstance. The only time-consuming work or the actual Apple search ads checking work is done on a different queue called `isolationQueue`. My understanding is it doesn't block the main queue or delay the app startup time? Is that correct?

**Comment by echo-branch** [comment]
@rongboyang 
You are correct.  The documentation is referring to SDK start up time.  However, if you need something from the SDK very early in your app lifecycle, that will be delayed.

**Comment by rongboyang** [comment]
@echo-branch,
Thanks for your quick response!
As to the SDK startup time, can you be more specific? What are the functions that will be affected by the delay? For example, is the deep link function affected by the delay? 

Thanks!

**Comment by echo-branch** [comment]
@rongboyang 
Nearly all SDK functions will wait for Search Ads to complete.  This does include deeplinking.  It's only on the very first open, so most often you're looking at a bit of a delay on deferred deeplinks.
