### ISSUE TITLE
BranchUniversalObject.getShortUrl calls back in thread inconsistently

### ISSUE THREAD

**Issue by ptsochantaris** [BranchMetrics/ios-branch-deep-linking-attribution#1004]
This method used to always call back in the main thread, and it still does upon first use, but now it will call back in background threads.

To reproduce, just call it a few times trying to share the same object.

It seems the first time calls back in the main thread as before, but then the second time, when the result is cached I imagine, it calls back on a background thread. This is causing our app to have unexpected crashes after upgrading the SDK.

We will work around it by putting async dispatch blocks to the main queue in the callbacks, but ideally this new unexpected behaviour is a stability landmine and should be corrected.

```
let branchUniversalObject: BranchUniversalObject = BranchUniversalObject(canonicalIdentifier: ...)
branchUniversalObject.getShortUrl(with: linkProperties) { link, error in
  // calls in main thread as expected
}
```

Then later on in the app lifecycle, repeating the call:

```
let branchUniversalObject: BranchUniversalObject = BranchUniversalObject(canonicalIdentifier: [same item as above])
branchUniversalObject.getShortUrl(with: linkProperties) { link, error in
  // calls in internal queue now!
}
```

**Comment by echo-branch** [comment]
This should be fixed.
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/0.32.0

**Comment by Natelegreat1** [comment]
Calling `getShortUrl` on Branch 1.44.0 using SwiftUI is showing the following:

``` warning run: This method should not be called on the main thread as it may lead to UI unresponsiveness.```

I get the same warning when using the callback:
`buo.getShortUrl(with: properties) { urlString, error in`

**Comment by jf-branch** [comment]
@Natelegreat1 Could you provide us with a code snippet of the UI block or how you are calling it?
