### ISSUE TITLE
Unable to determine if latest release is stable

### ISSUE THREAD

**Issue by philfi** [BranchMetrics/ios-branch-deep-linking-attribution#1005]
The commit for the latest release (https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/0.31.4) is showing a red checkmark due to some CI failure that isn't publicly visible. As a developer on a project using the Branch SDK it's unclear whether this release is stable (likely just some blip on the CI, it happens) or if there is a real issue to be concerned about.

If you could, we would appreciate you re-running/fixing as necessary so there isn't a cause for concern. Thanks in advance!

![image](https://user-images.githubusercontent.com/39564615/75472806-17d93780-5962-11ea-90db-15c1b7cbec98.png)

**Comment by philfi** [comment]
Seeing a new release available that passed all CI, closing.

**Comment by philfi** [comment]
Reopening as this is an issue again. @echo-branch I trust you are ensuring your release builds are stable but this raises concerns as a consumer of this SDK. Please resolve the failures or disable tests/CI as necessary if they aren't important.
![image](https://user-images.githubusercontent.com/39564615/81109327-ed6aa400-8ee7-11ea-952b-7cd85a3bb849.png)

**Comment by echo-branch** [comment]
We've moved off CircleCI and it's no longer being maintained.  I'll remove the integration in the next release.

**Comment by philfi** [comment]
Got it, I figured it was all good just needed that context. Thanks!
