### ISSUE TITLE
BranchEvent customData changed in 0.31

### ISSUE THREAD

**Issue by willbattel** [BranchMetrics/ios-branch-deep-linking-attribution#1006]
We're attempting to upgrade the SDK from `0.30.1` to `0.31.4`, and we're encountering an error showing that `BranchEvent.customData.addEntries(from:)` no longer exists. Referencing the README of this repository, we then tried to directly set the `customData` field with a `String: Any` dictionary, like we do with Firebase Analytics. However, it appears that `customData` takes only `String: String` values. Is this intentional? Can you please provide clarification on how this feature has changed, because we see no mention of it in the release notes. Thanks!

**Comment by willbattel** [comment]
I noticed the README is being changed to point to the new SDK docs here: https://help.branch.io/developers-hub/docs/ios-sdk-overview

When I navigate to the Events section of the Advanced Features page here: https://help.branch.io/developers-hub/docs/ios-advanced-features#section-track-events, it seems the Custom Events link is dead. Are there up-to-date docs on custom events?

**Comment by echo-branch** [comment]
@willbattel 
Sorry for the delay.  I'll let the docs team know about the broken docs link.

As for the API change it is mentioned as a generic safety improvement.
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/0.31.0

The actual change is customData is no longer mutable.  It was a potential threading issue.
