### ISSUE TITLE
Deep link handling block not called when tapping a link in terminated state

### ISSUE THREAD

**Issue by andersfrank** [BranchMetrics/ios-branch-deep-linking-attribution#1011]
Hi,
We see issues with the deep link handling block not being called, when tapping a link when the application is in a terminated state. The deep link handling block is not called at all. Se the bug report below. The issue can be reproduced in version `0.29.1` as well as `0.31.4`

#### Prerequisites
Add the following snippet to `AppDelegate.application(:didFinishLaunchingWithOptions)`:
```
Branch.getInstance()?.initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: { (params, error) in
    print("Should be called at every application launch")
})
```

#### Steps to reproduce
1. Terminate the application 
2. Tap a branch link, for example https://majority.test-app.link/0V56vjZoV4

#### Expected result
The deep link handling block provided at initSession should be called with params matching the tapped link.

#### Actual result
The deep link handling block is not called at all. Not even with empty parameters. As stated in the documentation it should:
> 100% of the time the app opens, it will call the deep link handling block to inform you whether the user came from a link

Cheers,
Anders Frank

**Comment by aureliensibiril** [comment]
We do have the exact same issue here. The block is not called.

**Comment by derrick-branch** [comment]
@andersfrank @aureliensibiril can you ensure you've implemented all of the methods in the AppDelegate file? If you have implemented all methods listed [here](https://help.branch.io/developers-hub/docs/ios-basic-integration#section-initialize-branch), and this still occurs, please write in to support@branch.io.
