### ISSUE TITLE
Push Notification Links not working properly if application is already open.

### ISSUE THREAD

**Issue by fchauvin** [BranchMetrics/ios-branch-deep-linking-attribution#1017]
If my app is open and I tap on a notification from the System Notification Center UI, the `initSession` callback block doesn't get called when the app is brought back into foreground. If I background the app, the block then gets called properly with the associated metadata.

I didn't see an existing issue with this behaviour, so am opening a new ticket.

**Comment by echo-branch** [comment]
Logging a ticket for this one.
