### ISSUE TITLE
Deprecated Webview, please change it to WKWebview

### ISSUE THREAD

**Issue by johnharutyunyan** [BranchMetrics/ios-branch-deep-linking-attribution#1019]
I have received warning mail from Apple today and it contained following.

**ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.**

I have searched in my app and understood that it is from your side , guys :) 

<img width="1276" alt="Screen Shot 2020-04-07 at 14 58 06" src="https://user-images.githubusercontent.com/26871856/78661668-3bd45500-78e0-11ea-8eb5-1d65b6c68431.png">

Guys, please change it, because after **December 20, all apps will be rejected.**

**Comment by philfi** [comment]
This has been previously resolved, try updating your version of Branch: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/931
