### ISSUE TITLE
Build warning for umbrella header when built with Carthage

### ISSUE THREAD

**Issue by gapl** [BranchMetrics/ios-branch-deep-linking-attribution#1020]
When using Branch framework with Carthage, Xcode compiler shows the following warning in the console:

```
<module-includes>:1:1: Umbrella header for module 'Branch' does not include header 'BranchScene.h'
```

Our `Cartfile.resolved` file:

```
[...]

github "BranchMetrics/ios-branch-deep-linking" "0.33.0"

[...]
```

**Comment by echo-branch** [comment]
This should be fixed in 0.33.1

Totally failed to add that header to the umbrella.
