### ISSUE TITLE
How to get content URI from mobile App for deep-linking for Branch.io quick link?

### ISSUE THREAD

**Issue by Jamessmith878889** [BranchMetrics/ios-branch-deep-linking-attribution#1023]
I have created a React Native app using third party which creates News posts.I have the entire code for this. How to get the full path (Mobile app URI) of a content/news post.

For example if I am posting a News and I need the full Path for that particular News for Deep-Linking. Like we get the path in the website https://www.example.com/post/1 , similarly what will the path in mobile app & where do I check in the code?

**Comment by echo-branch** [comment]
The link data payload from Branch will be returned in the Branch callback, the details will vary by platform.  From there, it is up to each app to decide on a routing architecture for the rest of the their app.  There's a several common approaches, but I can't tell you what your 3rd party app developers chose to use.   

Please contact support for help on implementation or general information on Branch links.  The github is usually only checked for potential bug reports or feature requests.
