### ISSUE TITLE
Deferred deep link is empty when install the app (Open the link with Chrome browser)

### ISSUE THREAD

**Issue by doanduchieu** [BranchMetrics/ios-branch-deep-linking-attribution#1025]
On iOS, after fresh installation of the application with the link on Chrome, deferred deep link is empty
Here are steps:
1. Clicking on a Branch link.
2. Navigate to Chrome browser.
3. Install the app then open -> Deferred deep link is empty.

It is working fine if open link by Safari browser.

**Comment by echo-branch** [comment]
Server team reports a fix for this is being tested and should deploy this sprint.

**Comment by raza08** [comment]
@echo-branch 
Hello,
I am facing the same issue, my app is killed and I'm clicking on deep-linking url at the same time app is opened but didn't get the data from URL.

**State** : 
1. App killed.
2. Clicked on branch deep link URL.
3. App opened 
4. After the app open didn't get any data from the URL.

**Note**: I'm getting data when an app is in the background.

**Comment by echo-branch** [comment]
Server team reports the fix shipped.  Could you verify if it's working for you?  Thanks.

**Comment by raza08** [comment]
@echo-branch  It's still not working with the killed app.

**Comment by echo-branch** [comment]
@raza08 
Is your issue exactly the same?  For example, is it specific to Chrome or does it occur on all browsers?

Also are you using UIScenes?  There's a known issue where Apple does not callback on a killed app, there's a workaround on our docs page.

https://help.branch.io/developers-hub/docs/ios-basic-integration#section-apps-using-scenes

**Comment by raza08** [comment]
@echo-branch I'm getting these issues when I click on other social media platforms like Whatsapp, Facebook.

And I'm not using UIScenes.

**Comment by doanduchieu** [comment]
> Server team reports the fix shipped. Could you verify if it's working for you? Thanks.
Hi @echo-branch , it's working for us. You can close this issue.
