### ISSUE TITLE
Deeplink handler triggered on appDidBecomActive interferes with Sign in with Apple flow

### ISSUE THREAD

**Issue by mrcperello** [BranchMetrics/ios-branch-deep-linking-attribution#1028]
**Issue**

DeeplinkHandler is triggered on `appDidBecomActive` and this shouldn't be an issue until we aim to use SIwA. Which is perfomed with a system sheet that when dismissed triggers `appDidBecomeActive` and then deeplinkHandler is called again.

As of now we are overcoming this storing the params and only reacting when they are different, however it'd be nice that this is handled by the API internally.

**Comment by echo-branch** [comment]
Thanks for the heads up.  Looking into this.

**Comment by mrcperello** [comment]
Do we have any follow-up on this? It's still an issue for us :(

**Comment by echo-branch** [comment]
Unfortunately we've been unable to implement the feature as requested. The main issue is that the change would negatively impact other integrations. Considering there is a workaround, we're going to close this as it's been languishing in the feature request backlog for a long time.
