### ISSUE TITLE
Getting Last Touch Attributed Data

### ISSUE THREAD

**Issue by akhilpothana** [BranchMetrics/ios-branch-deep-linking-attribution#1033]
**SDK version 0.33.1**

Hey, to preface I'm not sure my issue is related to incorrect documentation, a bug in the SDK or incorrect implementation on my end. That said, there is a discrepancy between the documentation and how the code behaves, so I thought this may be the best place to bring it up.

I'm specifically implementing the following:
https://help.branch.io/developers-hub/docs/retrieving-branchs-last-attributed-touch-data#ios

The docs say `If you do not provide a value within the SDK, Branch will use the attribution window setting value in your Branch dashboard`, but the code forces me to provide value. Digging into the SDK, I see this:

```
+ (void)requestLastTouchAttributedData:(BNCServerInterface *)serverInterface key:(NSString *)key attributionWindow:(NSInteger)window completion:(void(^) (BranchLastAttributedTouchData *latd))completion {
    BranchLATDRequest *request = [BranchLATDRequest new];
    
    // Limit attribution range to about a year.  Although the server only supports up to 90 days as of Nov. 2019, it will fail gracefully for higher values.
    if (window > -1 && window < 365) {
        request.attributionWindow = window;
    } else {
        BNCLogWarning(@"Attribution window is outside the expected range, using 30 days.");
    }
    
    [request makeRequest:serverInterface key:key callback:^(BNCServerResponse *response, NSError *error) {
        
        // error is logged by the network service, skip parsing on error
        if (error) {
            if (completion) {
                completion(nil);
            }
            return;
        }
    
        BranchLastAttributedTouchData *latd = [self buildFromJSON:response.data];
        if (completion) {
            completion(latd);
        }
    }];
}
```

It just looks like I can either specify a window, or pass a negative number in which case it defaults to 30 days. So how am I supposed to enable LATD without interfering with attribution window value that we set in our dashboard?

**Comment by echo-branch** [comment]
Yea that usability is a bit awkward.  Just off the top of my head, I believe 0 will get you the behavior you want.

**Comment by akhilpothana** [comment]
@echo-branch Hmm, it seems like 0 will be accepted as a valid value and used as my attribution window. 

```
if (window > -1 && window < 365) {
    request.attributionWindow = window;
}
```

So maybe I need to say `-2` or something?

**Comment by echo-branch** [comment]
0 will be sent to the server as the attribution window and since it's not a valid attribution window, the server will use the default server side value.  It's the only invalid attribution window we send up.  The API would probably make more sense if we used -1 or any negative number the same way.

**Comment by akhilpothana** [comment]
I see, thanks for clarifying that. Does it make sense for me to open a PR or is it best to just update the documentation?

**Comment by echo-branch** [comment]
I think a documentation clarification makes the most sense now.

**Comment by echo-branch** [comment]
clarification was added to the header doc on staging
