### ISSUE TITLE
Request: more detailed change logs

### ISSUE THREAD

**Issue by willbattel** [BranchMetrics/ios-branch-deep-linking-attribution#1039]
My team has been using Branch in our projects for a while and one thing we would really appreciate if possible would be expanded change logs. Adding short descriptions to each item and notes on breaking or suggested changes for developers would be really helpful for us! It doesn't have to be a lot- but frankly the current change logs are too ambiguous and force us to dive into the source code every time we want to update.

**Comment by echo-branch** [comment]
Since the 035.0 release we've been trying to put in more descriptive release notes.  Hopefully that has addressed this issue.
