### ISSUE TITLE
Missing modulemap file in Branch_tvOS Carthage framework

### ISSUE THREAD

**Issue by aerviti** [BranchMetrics/ios-branch-deep-linking-attribution#1047]
We're using Carthage in our project to download and manage the Branch frameworks and are planning to implement it for both iOS and tvOS.

We have noticed that there is no modulemap file included with the Branch_tvOS framework. However there is one included in the iOS Branch framework. This has blocked us from importing Branch into our swift files linked to the tvOS build.

**Comment by echo-branch** [comment]
Thanks for the heads up.

**Comment by echo-branch** [comment]
Does build from source work?  If I recall correctly, I didn't add a pre-built framework for tvOS.  Ran out of time and had to ship without it.  

`carthage update --no-use-binaries`

**Comment by echo-branch** [comment]
Fix should be in staging.  Working on a release.

**Comment by echo-branch** [comment]
This was released a while ago.  I forgot to close this.
