### ISSUE TITLE
Sometime metada is not available

### ISSUE THREAD

**Issue by MRodSebastian** [BranchMetrics/ios-branch-deep-linking-attribution#1051]
Im trying to recover custom parameters of a link, but sometimes I recover only these 3 parameters:

````
{
   "non_branch_link":"yourscheme://open?link_click_id=825324398017561760",
   "+is_first_session":0,
   "+clicked_branch_link":0
}
````

and other times i can recovery more info, like these
````
{
   "action":"test",
   "$one_time_use":0,
   "+click_timestamp":1598011683,
   "$ios_passive_deepview":"branch_passive_default",
   "$marketing_title":"Test iOS",
   "~id":824603007689280436,
   "+clicked_branch_link":1,
   "~referring_link":"https://oydox.test-app.link/y4hehxYQ48",
   "+is_first_session":0,
   "+match_guaranteed":1,
   "~creation_source":1,
   "~feature":"marketing",
   "~marketing":1
}
````
Parameter `action` is a custom parameter.
Any idea why this may happen? Im looking at the configuration and everything seems to be correct

**Comment by chunyili200556** [comment]
Same issue here. But in my case, sometimes get those 3 wrong parameters when installed my app by click the deeplink. But I need correct response every time after install app.

**Comment by anoop-mohandas** [comment]
I'm facing a similar issue, where in no parameters is received other than two values, "+clicked_branch_link" and "+is_first_session". If the app is installed it will have the ""~referring_link" but nothing more. Can anyone guide me here. I'm trying to use a "deferred deep link" case.

**Comment by KeiroMidori** [comment]
I am seeing the same thing on my end with iOS 13.7 and Xcode 11.7. Any ETA on a resolution for this?

**Comment by igar6** [comment]
I am facing the same issue. I get the correct response when app is running on background, but not when it must be opened first.

**Comment by ashalva** [comment]
We have the same issue here, the universal links are not working when the app is installed from the AppStore via the link. We found the issue recently, so it can be related to new restrictions of fingerprinting from Apple.

**Comment by leo1mml** [comment]
Same thing here 😞  I couldn't find a workaround until now.

**Comment by colealanroberts** [comment]
> Same thing here 😞 I couldn't find a workaround until now.

Hey, curious what workaround you found.

**Comment by Vasault** [comment]
having the same issue here and still haven't found a solution :(

**Comment by florohaltero** [comment]
Yeah I have still the same issue and I am wondering why there isnt any solution.. Deep links are just unusable
