### ISSUE TITLE
Make IDFA-code external or hide behind a macro to prepare for iOS 14

### ISSUE THREAD

**Issue by cruzach** [BranchMetrics/ios-branch-deep-linking-attribution#1052]
I know this was brought up in other issues, (https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/601, https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1049) but I just thought I'd add some more detail and hopefully provide some possible solutions.

To avoid any trouble with the App Submission process, it would be nice to completely eliminate [Branch's IDFA-related code](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/BNCSystemObserver.m#L49-L70) if we're not planning on collecting the IDFA anyways. This has the added benefit that developers wouldn't need to check the "My app uses the IDFA" box upon app submission

This was done in some other libraries that relied on IDFA:
- Segment externalized the code so that you have to provide the IDFA yourself- https://github.com/segmentio/analytics-ios/pull/892/files
- Amplitude put the IDFA code behind a macro - https://github.com/amplitude/Amplitude-iOS/commit/cbcf7d64b1e25301843f295ac3f000a2a22ba65e

This would be a huge help for people relying on the Branch iOS SDK but not collecting the IDFA, since I'm sure with iOS 14 and the new privacy changes, app rejections for IDFA collection (like those in the issues I linked to above) will become even more common

**Comment by echo-branch** [comment]
@cruzach 
I've added a macro BRANCH_EXCLUDE_IDFA_CODE to ease your concerns.  You can enable in your builds to exclude the code for IDFA.  Note that this will only work if you are building from source, a prebuilt framework will not respect the macro.

I don't think it's technically necessary as probing for frameworks via selectors generally does not trigger rejections from Apple.  It's only if AdSupport.framework is linked against that App that Apple raises concerns.  Now, Apple could always change the review process and flag this type of code as well, but historically they have not.

The problem with RN is that we default included AdSupport.framework and children's apps are not allowed to include it.  That's being fixed.

**Comment by cruzach** [comment]
Thanks for the quick response!

True, it may not be necessary, but there just doesn't seem to be very much information out there on what these IDFA changes mean (is the prompt shown when you ask for the IDFA, or when the app is installed? will existing apps not using the prompt be removed?) so it may be better to be safe than sorry in that case. 

> The problem with RN is that we default included AdSupport.framework and children's apps are not allowed to include it. That's being fixed.

Oh that's great to hear! Would you happen to know the timeline for this?

**Comment by echo-branch** [comment]
The IDFA prompt must be requested by the app developer via the AppTrackingTransparency framework.  It is not automatically triggered by attempting to request the IDFA.
https://developer.apple.com/documentation/apptrackingtransparency

Every request for IDFA before permission is granted will return 0's, just like an iOS 13 user with privacy enabled.  

Since IDFA permission is decoupled from fetching IDFA, it's easier to have a rich process around requesting IDFA permission while not mucking up the code to use IDFA.  

For RN, we're hoping to get all the iOS SDKs updated this week.

**Comment by cruzach** [comment]
That's great news, thanks!

**Comment by warpling** [comment]
@echo-branch Thank you for adding this!
