### ISSUE TITLE
Setting setTrackingDisabled:true before initSessionWithLaunchOptions will cause handler returning an error

### ISSUE THREAD

**Issue by benv33** [BranchMetrics/ios-branch-deep-linking-attribution#1059]
Branch SDK version: 0.35.0
Language: obj-C

Hi,

If I disable tracking before the initialization I always get an error in the handler block. 

```
Branch *branch = [Branch getInstance];
    [Branch setTrackingDisabled:YES];
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        if (error) {
            NSLog(@"%@",[error localizedDescription]);
        }
        else {
            //Get link data
        }
    }];
```

**_BNCServerInterface.m(252) Error: Network service error: Error Domain=io.branch.sdk.error Code=1015 "User tracking is disabled and the request is not on the whitelist" UserInfo={NSLocalizedDescription=User tracking is disabled and the request is not on the whitelist}._**

I can call `[Branch setTrackingDisabled:YES];` inside the handler but I not sure if it will trigger some user tracking requests, something I really don't want.

Thanks,
Benoit

**Comment by echo-branch** [comment]
@benv33 
Your implementation looks correct.  

When tracking is disabled, we drop all PII and only allow link resolution and link creation calls.  We overloaded the error system to inform you that we dropped a request.

In an ideal situation we would have used the more typical status callback, however the way our network code is designed, the status callback occurs AFTER a network call.  Which would be too late to comply with GDPR, so we settled on this solution until we can refactor our network stack.

**Comment by benv33** [comment]
Are PII used for matching when user click link -> app install -> open the app because with my implementation I get an error and empty data? Because for this use case I would need to disable tracking in the handler and not before init.

**Comment by echo-branch** [comment]
Only for deferred deeplinks, these do not work with tracking disabled.  For regular links we do not use PII.  

Could you confirm that the raw link is coming in via continueUserActivity?  When you use a universal link on iOS, the click -> app open happens all on the device side.  Nothing is sent to the Branch server.  On app open, we then use the universal link to look up the data associated.  When requesting it, we send only the link itself and some non-PII information.

**Comment by benv33** [comment]
On click link -> first app install -> open app the continueUserActivity is not called. Once the app is downloaded, if I click the same link continueUserActivity is called.

**Comment by echo-branch** [comment]
Oh wait. I totally missed the first app install part.  That's a deferred deeplink, which does rely on PII.  That feature will not work on with tracking disabled.

**Comment by benv33** [comment]
God to know, maybe I missed this information in the doc and if not it would be good to add a mention to this.

Thanks
