### ISSUE TITLE
0.28.0 still uses UIWebView

### ISSUE THREAD

**Issue by sudeepdino008** [BranchMetrics/ios-branch-deep-linking-attribution#1063]
In https://blog.branch.io/how-to-prepare-for-apples-uiwebview-deprecation/, the text says 

> Starting with the Branch iOS SDK version 0.28.0 and TUNE iOS SDK version 6.2.0, Branch no longer uses UIWebView. 

I updated Branch version to 0.28.0, and it still was using UIWebView. I then updated it to 0.29.0, and it didn't rely on UIWebView and was replaced. 

The above quoted text is misleading as 0.28.0 uses UIWebView.

**Comment by echo-branch** [comment]
I was not able to reproduce the issue.  Maybe the build was cached with an older SDK binary?  Either way, 0.28.0 is rather old and newer integrations should use the latest possible version.
