### ISSUE TITLE
Update BNCCrashlyticsWrapper to use Firebase Crashlytics

### ISSUE THREAD

**Issue by JesseScott** [BranchMetrics/ios-branch-deep-linking-attribution#1067]
## Outline
* As per the Fabric -> Firebase migration, the Crashlytics SDK is being turned off on November 15th, 2020.

## Issue
* It seems that the BNCCrashlytics class that is  part of the Branch SDK still uses the Fabric implementation

## Docs
* https://firebase.google.com/docs/crashlytics/upgrade-sdk?authuser=0&platform=ios

**Comment by nsingh-branch** [comment]
BNCCrashlytics has been updated to support Firebase.
