### ISSUE TITLE
Crash inBNCLog.m - Line 629

### ISSUE THREAD

**Issue by kvyat** [BranchMetrics/ios-branch-deep-linking-attribution#1071]
Hi, we have some crashes with Crash in BNCLog.m - Line 629. We use the latest version of Branch pods but it happens with every version.
<img width="1272" alt="Screenshot 2020-11-09 at 2 24 34 PM" src="https://user-images.githubusercontent.com/25620329/98541370-00e03880-2298-11eb-8954-f8548edd82ac.png">

**Comment by echo-branch** [comment]
Could you try deleting all the cache'd pods and build files?  Then rebuilding?  There was a macro redefinition in the logger and cache'd version of it could cause a failure like that.

**Comment by kvyat** [comment]
> Could you try deleting all the cache'd pods and build files? Then rebuilding? There was a macro redefinition in the logger and cache'd version of it could cause a failure like that.

I'll try, thanks

**Comment by echo-branch** [comment]
I'll assume the issue was resolved and the reporter will reopen if it wasn't.
