### ISSUE TITLE
Cocoapods could not be updated

### ISSUE THREAD

**Issue by LimCrazy** [BranchMetrics/ios-branch-deep-linking-attribution#1076]
<img width="978" alt="WeChatc70f52f8439d2bb0c47ebf9d898895e0" src="https://user-images.githubusercontent.com/17854709/103255563-b9874600-49c4-11eb-8565-d16b8274f1e6.png">

I've been stuck here. I can't move. Why is that？

**Comment by echo-branch** [comment]
I wasn't able to reproduce your issue this morning, however I did see a couple reports of issues with cocoapods last night.  Could you try it again today?

Another possibility is checking the Podfile min version 9.  Though I'm pretty sure that gives a different error message.

**Comment by echo-branch** [comment]
Haven't heard back.
