### ISSUE TITLE
xcode 12 xcframework support

### ISSUE THREAD

**Issue by mmdumi** [BranchMetrics/ios-branch-deep-linking-attribution#1079]
Hi,
carthage is ready to compile frameworks as xcframework
Would you please be able to provide the Branch sdk as xcframework ? We can't compile our project on M1 macs because of Branch.
Thank you.

**Comment by echo-branch** [comment]
The 0.37.0 release added support xcframeworks. You will need to install carthage from source until the ` --use-xcframeworks` flag is supported in the general carthage release.

Still working on updating our docs to account for the 0.37.0 release.
