### ISSUE TITLE
IOS 14+

### ISSUE THREAD

**Issue by vWolfG** [BranchMetrics/ios-branch-deep-linking-attribution#1080]
I have tried the following demo https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-iOS
Also, I created my own empty project according to the documentation https://help.branch.io/developers-hub/docs/ios-basic-integration, both of them don't work on the ios 14.2 and 14.3 devices, however, it works on the ios 13.7 and lower.
Deeplink was opened in the safari and was redirected to the custom link or AppStore(depends on configuration), but it didn't open the app.

Please, could you help me to fix that problem and make it work on ios 14 +?
- Branch (0.36.0)
- Xcode 12.3

**Comment by vWolfG** [comment]
Have found the information here https://help.branch.io/faq/docs/what-code-do-i-need-to-add-to-include-the-idfa-prompt

**Comment by cavenugs** [comment]
- [

**Comment by cavenugs** [comment]
> I have tried the following demo https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-iOS
> 
> Also, I created my own empty project according to the documentation https://help.branch.io/developers-hub/docs/ios-basic-integration, both of them don't work on the ios 14.2 and 14.3 devices, however, it works on the ios 13.7 and lower.
> 
> Deeplink was opened in the safari and was redirected to the custom link or AppStore(depends on configuration), but it didn't open the app.
> 
> 
> 
> 
> 
> Please, could you help me to fix that problem and make it work on ios 14 +?
> 
> - Branch (0.36.0)
> 
> -branch/docs/-integration-instructions
