### ISSUE TITLE
App Crashes on Launch

### ISSUE THREAD

**Issue by TarasGordienko** [BranchMetrics/ios-branch-deep-linking-attribution#1098]
App is crashing while installing build with Branch 1.39 on iPhone with iOS 13.3:

dyld: Library not loaded: /System/Library/Frameworks/AdServices.framework/AdServices

can be related to adding https://developer.apple.com/documentation/adservices to the podspec (as it requires iOS 14.3+)

**Comment by echo-branch** [comment]
Thanks for the heads up. Are you able to provide the Xcode version you are using?

**Comment by wammy67** [comment]
My version is 12.4.

**Comment by echo-branch** [comment]
I was able to repro the issue, working on a patch release.  Probably be out tomorrow.

**Comment by ilkerc** [comment]
Same issue, Xcode Version 12.4 (12D4e)
```
dyld: Library not loaded: /System/Library/Frameworks/AdServices.framework/AdServices
  Referenced from: /private/var/containers/Bundle/Application/A2800214-5529-434F-9674-D91E8454F32B/app.app/app
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib
```

**Comment by IgorFedorchuk** [comment]
Вангую, что тут накостылили
http://joxi.ru/vAWM65jsOMKlWm

**Comment by IgorFedorchuk** [comment]
Maybe this is the reason (Вангую, что тут накостылили)
http://joxi.ru/vAWM65jsOMKlWm

**Comment by umerasif** [comment]
Getting the error `Module 'AdServices' not found` while compiling code in file BNCSystemObserver.m

```
#if __has_feature(modules)
@import AdServices;
#else

```

**Comment by maughray** [comment]
Same issue.

**Comment by umerasif** [comment]
These might help to solve the backwards compatibility problem

https://stackoverflow.com/questions/52605302/swifts-canimport-analogue-in-objective-c
https://stackoverflow.com/questions/24380340/error-after-importing-swift-into-objective-c

**Comment by ArthurNarimanov** [comment]
Decision:  https://developer.apple.com/forums/thread/673708

**Comment by echo-branch** [comment]
Released patch version 1.39.1 that addresses this by not including the framework by default. Let me know if you have any issues with it.

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/1.39.1

**Comment by trongnhan68** [comment]
> Decision: https://developer.apple.com/forums/thread/673708

Amazing, Good job boy.
This solution worked for me. Thanks.

**Comment by umerasif** [comment]
> Released patch version 1.39.1 that addresses this by not including the framework by default. Let me know if you have any issues with it.
> 
> https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/1.39.1

Still getting the error `Module 'AdServices' not found` :(
I am using Xcode 12.1

**Comment by echo-branch** [comment]
@umerasif 
Could you try using the current Xcode release, 12.4? We generally support just the most recent versions as Apple tends to stop supporting older versions pretty quickly.

**Comment by umerasif** [comment]
Yes, we have decided to move to 12.4 👍

**Comment by MalcolmScoffable** [comment]
Still getting this error using Xcode 12.5 on iOS 13.5. Works fine in iOS 14+ but has been affecting some of our users. Just tested using a 13.5 simulator and getting the following error message:
```
dyld: Library not loaded: /System/Library/Frameworks/AdServices.framework/AdServices
  Referenced from: [APP Path]
  Reason: image not found
dyld: launch, loading dependent libraries
```

**Comment by MalcolmScoffable** [comment]
OK, I managed to get this to work by making the `AdServices.framework` library optional as per the following screenshot:

<img width="1000" alt="Screenshot 2021-05-17 at 11 31 50" src="https://user-images.githubusercontent.com/24914554/118474998-9d7e0a00-b703-11eb-8206-5b0766513ba8.png">

Not sure if it's just that this lib isn't available on iOS 13 but I do think the documentation should be updated to inform users how to set this up. Otherwise the Branch SDK crashes the app on iOS 13 on startup.
