### ISSUE TITLE
registerFacebookDeepLinkingClass not working

### ISSUE THREAD

**Issue by dschmierer** [BranchMetrics/ios-branch-deep-linking-attribution#1107]
Calling `registerFacebookDeepLinkingClass` seems to cause the init to fail.

```swift
Branch.getInstance().registerFacebookDeepLinkingClass(AppLinkUtility.self)
Branch.getInstance().initSession(launchOptions: launchOptions)
```

I'm using the latest versions of the SDKs although this seems to happen with FB 9.0 SDK as well:

`pod 'FBSDKCoreKit', '9.2.0'`
`pod 'Branch', '1.39.2'`

**Comment by echo-branch** [comment]
Thanks for the heads up on that change!

**Comment by darko55555** [comment]
Hey, I had the same issue. It was the same error but I am not using FBSDK. Tracked it down to 
```
+ (NSString *)appleAttributionToken {
#if !TARGET_OS_TV
    if (@available(iOS 14.3, *)) {
        NSError *error;
        NSString *appleAttributionToken = [AAAttribution attributionTokenWithError:&error];
        if (!error) {
            return appleAttributionToken;
        }
    }
#endif
    return nil;
}
```
in iOS14.5/Xcode12.5 there are new requirements from Apple, thus this will fail, but error and appleAttributionToken will be nil ,therefore it will never hit return (which is a bad programming from Branch side, or apple's that doesn't return error for some reason).

+ (NSString *)appleAttributionToken {
#if !TARGET_OS_TV
**return nil;**
    if (@available(iOS 14.3, *)) {
        NSError *error;
        NSString *appleAttributionToken = [AAAttribution attributionTokenWithError:&error];
        if (!error) {
            return appleAttributionToken;
        }
    }
#endif
    return nil;
}
```
Return nil fixed it for me since I only use deeplinking, not facebook.

**Comment by echo-branch** [comment]
@darko55555 
I think you missed that there is no else clause, it'll fall through and hit the last return nil. So the lack of an error makes no difference.

That code is unrelated to Facebook, it's for Apple Search Ads attribution. I'm curious what the error you were seeing is, since it's very likely to be different from what the initial reporter was seeing.

**Comment by darko55555** [comment]
As I've written, I'm not using FBSDK, and the error is on `appleAttributionToken`

**Comment by echo-branch** [comment]
@darko55555 
Can you open a new issue with this information?  I agree that what you are describing is not a FB SDK issue and should be handled as it's own ticket.  Thanks.

**Comment by echo-branch** [comment]
Moved to another ticket.
