### ISSUE TITLE
Empty deeplink data on fresh installed app

### ISSUE THREAD

**Issue by phuaan** [BranchMetrics/ios-branch-deep-linking-attribution#1108]
Hi,

I am having issues with opening a deeplink on app fresh install, the params from the deeplink handler is only "[\"+clicked_branch_link\": 0, \"+is_first_session\": 0]" 

It only happens when I do the following:
1. install the app from AppStore/test flight/Xcode, and don't open the app manually.
2. click the deep link -> will only get [\"+clicked_branch_link\": 0, \"+is_first_session\": 0]" .

The same deep link will work if I do the following:
1. click the deep link with the app not installed.
2. install the app from AppStore/test flight/Xcode.
3. open app -> will show other params too.

After some testing, I found that not all of our deep links experienced this, and only those that matched with the hardcoded regex from the BNCURLFilter class will fail. (the failing deep links contains the word "oauth" and matches with this regex "^(?i)((http|https):\/\/).*[\/|?|#].*\b(password|o?auth|o?auth.?token|access|access.?token)\b").

While running the example app, I found that the fetched regexes from the method updatePatternListWithCompletion do not match with my deep links(unlike the hardcoded regexes), I think this may explain why sometimes the deep link works and other times it doesn't. to test it, I made a new deep link containing the word "access" which will match with one of the regex, and as expected the deep link only returns [\"+clicked_branch_link\": 0, \"+is_first_session\": 0]".

If it is possible, could you explain the main use of the BNCURLFilter class, and why Branch filters some url? (since it is suspected to cause this issue)
and since it's not possible for me to change the deep link from containing the word "oauth"(as it's already in use in production) is there any fix for this issue?

**Comment by echo-branch** [comment]
Please reach out to our support team for help. They can help figure out any workarounds for edge cases and configuration issues.

https://help.branch.io/

**Comment by phuaan** [comment]
will do, thanks
