### ISSUE TITLE
Branch.io built w Xcode 12.5 hangs calling appleAttributionToken

### ISSUE THREAD

**Issue by darko55555** [BranchMetrics/ios-branch-deep-linking-attribution#1109]
Branch.io hangs calling this

```
+ (NSString *)appleAttributionToken {
#if !TARGET_OS_TV
    if (@available(iOS 14.3, *)) {
        NSError *error;
        NSString *appleAttributionToken = [AAAttribution attributionTokenWithError:&error];
        if (!error) {
            return appleAttributionToken;
        }
    }
#endif
    return nil;
}
```
in iOS14.5/Xcode12.5 there are new requirements from Apple, thus this will fail, but error and appleAttributionToken will be nil ,therefore it will never hit return since AAA doesn't return the response.

+ (NSString *)appleAttributionToken {
#if !TARGET_OS_TV
**return nil;**
    if (@available(iOS 14.3, *)) {
        NSError *error;
        NSString *appleAttributionToken = [AAAttribution attributionTokenWithError:&error];
        if (!error) {
            return appleAttributionToken;
        }
    }
#endif
    return nil;
}
```
Return nil fixed it for me since I only use deeplinking, not facebook.

_Originally posted by @darko55555 in https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1107#issuecomment-827558528_

**Comment by echo-branch** [comment]
I was unable to repro the issue you describe, but I do think that call to AAAttribution is blocking.  If there's a major delay in Apple responding, we might end up in a blocked as you describe. 

Checking for error won't help cause we'll be blocked waiting for that API respond.  I'll reach out to Apple for clarity on the behavior of that API.

For additional information, could you provide what device/simulator you're testing with and what region you're in?

**Comment by x0rb0t** [comment]
+1. I was investigating why short link generation hangs, and found the same problem

**Comment by darko55555** [comment]
Sure thing @echo-branch  , I'm using:
Xcode 12.5 with iPhone 12 Pro Max simulator on iOS 14.5

Region is Europe, Croatia but happens to my colleagues in the US too.
