### ISSUE TITLE
ATTrackingManager paused initialization for objective-c but not swift

### ISSUE THREAD

**Issue by ninjz** [BranchMetrics/ios-branch-deep-linking-attribution#1111]
In the docs [here](https://help.branch.io/developers-hub/docs/ios-advanced-features#include-apples-attrackingmanager) for Swift, it says to just go right into requesting the identifier, but for objective-c to pause the initialization of the SDK until the request has been made.

Is there different behaviours between the two or are the docs just not up to date?

**Comment by echo-branch** [comment]
@ninjz 
Thanks for the heads up on the docs mismatch.  For the current SDK version, the pause is not necessary. I'll work with the docs team to get that corrected.
