### ISSUE TITLE
Startup crash on iOS 13 due to no AdServices.framework

### ISSUE THREAD

**Issue by MalcolmScoffable** [BranchMetrics/ios-branch-deep-linking-attribution#1116]
I've noticed that the Branch SDK crashes our app on startup when running on iOS 13, and a number of our users have been affected by this. This only happens when the `AdServices.framework` library has been imported as recommended in the documentation here https://help.branch.io/developers-hub/docs/ios-basic-integration.

The error is as follows using the Xcode 12.5 on iOS 13.5. Works fine in iOS 14+. Just tested using a 13.5 simulator and getting the following error message:
```
dyld: Library not loaded: /System/Library/Frameworks/AdServices.framework/AdServices
  Referenced from: [APP Path]
  Reason: image not found
dyld: launch, loading dependent libraries
```

I've managed to get the app to work on iOS 13 by marking `AdServices.framework` as an optional dependency. However, it's not clear that this is required. Perhaps it would be worth updating the documentation to make this clear, or maybe there is an issue in the SDK. The following closed issue suggests that this has been fixed: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1098 however I've had this behaviour on versions 1.39.2 and 1.39.3 of the Branch SDK.

The workaround at the moment is to go to `Build Phases` -> `Link Binary With Libraries` and in there mark `AdServices.framework` as `optional`. As shown in the following screenshot:

<img width="1177" alt="Screenshot 2021-05-17 at 11 31 50" src="https://user-images.githubusercontent.com/24914554/118475745-88ee4180-b704-11eb-8fb8-38fbf9388a8f.png">

However, this behaviour isn't the default case when importing libraries in Xcode so I think it either needs to be better documented in the developer guide, or fixed otherwise (not sure what the best solution is).

I have added comments to the closed issue, but since this is affecting the latest versions I thought it would be worth reopening as a fresh issue.

**Comment by echo-branch** [comment]
I'll talk to the docs team about clarifying the wording around what we mean by the framework is optional.

**Comment by MalcolmScoffable** [comment]
Yeah, I think a walkthrough in the documentation on how to set this up in Xcode would be useful. There is more to it than just importing libraries so I think it's important to show how in order to avoid crashes on older operating systems. I don't normally work with iOS 13 these days so would be easy to miss that this was a problem.

**Comment by echo-branch** [comment]
@aparedes-branch

**Comment by Vasault** [comment]
I'm still struggling with this issue, but my problem is, I don't see any library on my workspace, in fact, in my case I can only see this libPods-nameofmyapp.a

**Comment by echo-branch** [comment]
@Vasault 
First could you verify you're on a recent version of Xcode? AdServices was added early this year and the current version of Branch SDK requires it.

**Comment by Vasault** [comment]
> @Vasault
> First could you verify you're on a recent version of Xcode? AdServices was added early this year and the current version of Branch SDK requires it.

that's exactly what I did yesterday, and indeed solved that issue in particular, but now the app is crashing instantly without showing any error whatsoever

**Comment by echo-branch** [comment]
@Vasault 
When you say without any error, not even the error mentioned above about library not loaded? Trying to figure out if you have the same issue as the original reporter or a different issue.

**Comment by jf-branch** [comment]
@Vasault Wanted to follow up and see if you were able to resolve the issue and if you could provide additionall insight into the reason behind those instant crashes as Echo mentioned previously.
