### ISSUE TITLE
Module 'AdServices' not found 

### ISSUE THREAD

**Issue by umairalisadapay** [BranchMetrics/ios-branch-deep-linking-attribution#1119]
I've integrated Branch using pod in my iOS project. Pod installed Branch 1.39.3 version. After installation, I'm trying to build a project but getting "Module AdServices not found" in BNCSystemObserver.m file.  For reference PFA the screenshot.

<img width="1424" alt="Screenshot 2021-05-20 at 9 40 16 PM" src="https://user-images.githubusercontent.com/76551402/119016987-f96eba00-b9b3-11eb-9659-c6486e524e25.png">

To build it successfully, I moved my Branch SDK version to 1.38.0.

**Comment by echo-branch** [comment]
The most likely cause is that you are building with an out of date version of Xcode.  AdServices.framework was added in Xcode 12.3.  Please confirm you are on the latest version of Xcode.

**Comment by umairalisadapay** [comment]
Yep, you are right. I was on an older version(12.2). Updated Xcode and issue resolved. Thanks for your supoort.
