### ISSUE TITLE
Undefined symbols for architecture x86_64:   "___llvm_profile_runtime"

### ISSUE THREAD

**Issue by sujitpoudel** [BranchMetrics/ios-branch-deep-linking-attribution#1130]
Hello! 

We are trying to adopt SPM to manage dependencies, but with the usage of most recent release of Branch on SPM, we get the issue: 
```
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
```
Curiously, this only happens when Branch is brought in as transitive dependency by another project within our modular arch.
This mostly can be suppressed by disabling Code Coverage. However, that is not an option for us.

And then I tried using most recent revision of master branch, and that seems to have no no problems at all. So, there seems to be some changes from last release in April to current state of master that fixes this issue. Is it possible to cut a new release from master anytime soon?

**Comment by sujitpoudel** [comment]
More info:
![image](https://user-images.githubusercontent.com/23458778/122087326-974a7e80-cdd2-11eb-9522-8026c61c3ade.png)

Fails in that clang command. But that line will work if I add a parameter `-fprofile-instr-generate` to clang command and try to manually run it. At this time, this is the only issue that is blocker for SPM adoption.

**Comment by Armenm** [comment]
Hi, we are having the same issue as well. Can anyone from the Branch team help?
@nsingh-branch Are you the best person to address this question?

Thanks

**Comment by Armenm** [comment]
<img width="1058" alt="Screen Shot 2022-08-03 at 5 30 59 PM" src="https://user-images.githubusercontent.com/1474183/182716076-9835acdb-87ea-4550-b3e5-f57bf369e430.png">
