### ISSUE TITLE
Module 'AdServices' not found

### ISSUE THREAD

**Issue by arun1989** [BranchMetrics/ios-branch-deep-linking-attribution#1140]
Hello Team, 

I just reviewed all suggestions given in basic iOS Integration and issues posted by other developers and check your demo app code as well, All have same issue of AdServices.framework missing, I'm trying to get this and try to add in Link Binary Libraries but didn't get this Can you give your suggestion how to overcome this issue...
<img width="814" alt="Screen Shot 2021-07-28 at 2 02 38 PM" src="https://user-images.githubusercontent.com/12507057/127373712-081f1021-0f1d-4bbf-a38e-e1f3ccfc96db.png">

**Comment by echo-branch** [comment]
@arun1989 

Could you confirm you're using the latest version of Xcode? The most common cause of this error is using an out of date version of Xcode. It requires Xcode 12.3 or higher.

**Comment by arun1989** [comment]
Thanks @echo-branch with Xcode 12.5 issue resolved...
