### ISSUE TITLE
Repo not structured properly for Swift Package

### ISSUE THREAD

**Issue by PatrickDanino** [BranchMetrics/ios-branch-deep-linking-attribution#1153]
Xcode is generating dozens of warnings about the Branch SDK when included via the SPM. These warnings cannot be turned off by default and are generating noise that hides other legitimate warnings.

Example of a warning when archiving:
Warning: Umbrella header for module 'Branch' does not include header 'BNCTuneUtility.h'`

SPM requires that the headers be split between two folders, one for public headers and the other for private headers. You can then specify the private folder as a _headerSearchPath_ and add it to the _exclude_ list in Package.swift. By default, public headers put in an _include_ folder will be automatically picked up.

**Comment by wvdk** [comment]
@PatrickDanino I see they have a separate repo for SPM. Perhaps that one has fewer warnings (haven't tried it yet). https://github.com/BranchMetrics/ios-branch-sdk-spm

**Comment by ismetanin** [comment]
We experienced the same issue and now we can't use Branch SDK with SPM
<img width="434" alt="image" src="https://user-images.githubusercontent.com/11653316/146341164-570c7686-126e-4573-8c80-e6f81e46a7b2.png">

**Comment by sbaropeak** [comment]
We have the same problem. Those warnings become errors when GCC_TREAT_WARNINGS_AS_ERRORS is enabled. We had to disable it, at least now.
We are using the SPM specific repo (https://github.com/BranchMetrics/ios-branch-sdk-spm) with version 1.40.2

**Comment by echo-branch** [comment]
We have this earmarked for end of quarter.

**Comment by jhk115** [comment]
Hi @echo-branch is there an update on this issue?

**Comment by echo-branch** [comment]
So it was in progress, but got shelved for other work. I'm picking it back up this next sprint.

**Comment by TaimoorSaeed** [comment]
+1

**Comment by shannoga** [comment]
@echo-branch Hi, any updates?

**Comment by shannoga** [comment]
@echo-branch Hi, any chance for updates?
Thanks

**Comment by echo-branch** [comment]
In progress. The layout refactor has cascading impact on our build, testing and documentation. So it's taking some time to get everything lined up.

**Comment by shannoga** [comment]
> In progress. The layout refactor has cascading impact on our build, testing and documentation. So it's taking some time to get everything lined up.

Thanks for the update

**Comment by jhurray** [comment]
@echo-branch any update here? This was fine for Xcode 13.4 but we';re getting tons of warnings in Xcode 14

**Comment by echo-branch** [comment]
@jhurray 
I suspect you had the type of warning ignored before, cause it's been an issue for almost a year now. 

We're still chipping away at the problem internally, the fix will require renaming our SDK which means updating a lot of docs, build and testing. We also have dependencies such as RN, Unity etc to manage along with this. Our initial 1 or 2 sprint estimate was way off. I don't have a firm date, but it'll be a major release.

**Comment by echo-branch** [comment]
This was shipped with 2.0.0
