### ISSUE TITLE
Why is this repository 724.25 MiB?

### ISSUE THREAD

**Issue by frogg** [BranchMetrics/ios-branch-deep-linking-attribution#1162]
It was impossible to import the swift package via Xcode, because the loading wouldn't stop.
So instead I decided to clone the repository manually and discovered that it‘s 724.25 MiB of size. Why?
![Screen Recording 2022-01-12 at 23 15 05](https://user-images.githubusercontent.com/5204169/149231942-ad4d07ac-5330-4c2a-8d71-01985311402f.gif)

**Comment by frogg** [comment]
ok, the documentation provides a good workaround:

```
Please use ios-branch-sdk-spm repo with Swift Package Manager


Please use the special https://github.com/BranchMetrics/ios-branch-sdk-spm repository with Swift Package Manager. This makes for much faster installation and a better experience using the Branch SDK with SPM due to the large size of the main iOS repo. The released contents are identical.

Note: The repository is no longer named ios-spm. If you installed using ios-spm, it will continue to work until you have a chance to change to https://github.com/BranchMetrics/ios-branch-sdk-spm. If you are installing for the first time, please use ios-branch-sdk-spm.
```

**Comment by GolfNoiise2020** [comment]
> It was impossible to import the swift package via Xcode, because the loading wouldn't stop.
> So instead I decided to clone the repository manually and discovered that it‘s 724.25 MiB of size. Why?
> ![Screen Recording 2022-01-12 at 23 15 05](https://user-images.githubusercontent.com/5204169/149231942-ad4d07ac-5330-4c2a-8d71-01985311402f.gif)

**Comment by echo-branch** [comment]
Current workaround is to the use the SPM specific repo. https://github.com/BranchMetrics/ios-branch-sdk-spm

Root cause is we used to commit the release binary to github, this leads to bloated repo history.
