### ISSUE TITLE
initSessionWithLaunchOptions is getting called with previously selected deeplink when user goes background and come foreground.

### ISSUE THREAD

**Issue by Thejusg** [BranchMetrics/ios-branch-deep-linking-attribution#1189]
Steps to Reproduce:

1. Click a deep link, gets redirected to the app with respective page.
2. close respective page and go to background and come foreground
3. initSessionWithLaunchOptions is getting called again with previously clicked deeplink.

please refer below code snippets of initializing Branch.

`let branchInstance: Branch = Branch.getInstance()
 branchInstance.initSession(launchOptions: options, andRegisterDeepLinkHandler: callback)`
 
 let us know if we missed some thing here or should we have to use different init function.

**Comment by Thejusg** [comment]
any update on this

**Comment by echo-branch** [comment]
Could you file a support ticket for this? I suspect this is an integration issue and not a bug.

https://help.branch.io/using-branch/page/submit-a-ticket

**Comment by Thejusg** [comment]
Hi BranchMetrics/ios-branch-deep-linking-attribution,

Please refer to this ticket number for more information ---> case number :
- 00276432.

**Comment by zijiaZ** [comment]
@echo-branch having the same issue, any updates?

**Comment by zijiaZ** [comment]
Seems returning it out fixes the issue if scene is nil, is it safe to do that? Thanks!
```
        BranchScene.shared().initSession(launchOptions: launchHelper.launchOptions, registerDeepLinkHandler: { [weak self] (params, error, scene) in
            guard scene != nil else { return }
            .......
          })
```

**Comment by AnshulSolankiSapient** [comment]
We are also facing the same issue in our project, it keeps triggering the code when the app is put in background and then brought back to foreground.
