### ISSUE TITLE
When we clicked on link branch.subscribe not triggering 

### ISSUE THREAD

**Issue by arun1989** [BranchMetrics/ios-branch-deep-linking-attribution#1192]
These are NPM lib i am using at the moment.
    "expo": "^40.0.1",
    "react-native-branch": "^5.5.0"

// listener
branch.subscribe(({error, params, uri}) => {
  if (error) {
    console.error('Error from Branch: ' + error)
    return
  }
  // params will never be null if error is null
})

let lastParams = await branch.getLatestReferringParams() // params from last open
let installParams = await branch.getFirstReferringParams() // params from original install

**Comment by gdeluna-branch** [comment]
Hi @arun1989 this is an integration issue- please submit a ticket via https://help.branch.io/using-branch/page/submit-a-ticket and they can help you from there.

Thanks
