### ISSUE TITLE
App crash on launching

### ISSUE THREAD

**Issue by zijiaZ** [BranchMetrics/ios-branch-deep-linking-attribution#1193]
hey guys,

The app, with lower iOS version, starts crashing after upgrading the SDK from 1.40.1 to the latest one, the team did some investigation and noticed it's because that adservice.framework is only available after iOS 14.3.

Is this change causing the issue? WDYT?

![Screen Shot 2022-09-06 at 11 50 10 AM](https://user-images.githubusercontent.com/81662792/188703886-753e5638-c74b-4193-a567-1e289fc414c3.png)

**Comment by echo-branch** [comment]
Are you using an old version of Xcode? This is known to occur on versions of Xcode that don't support AdServices.

**Comment by zijiaZ** [comment]
> 

hey @echo-branch , Im using Xcode 13.4.1

**Comment by echo-branch** [comment]
Is your dev environment the same as the environment that builds release binaries? All previous reports of this issue were due to using an out of date Xcode.

**Comment by zijiaZ** [comment]
Yes, Im able to repro it using my dev environment

1. macOS version:  **12.5.1**
2. cpu type: **Apple M1 Max**
3. xcode version: **13.4.1**
4. simulator or device model/version: **simulator iPhone 12(14.1)**
5. integration method: **SPM**

**Comment by echo-branch** [comment]
I wasn't able to repro on my own environment and test app, which is very similar to yours.

Just read over the issue description and release notes one more time. The Adservices code was in the 1.40.1 SDK as well, so it makes me think it could be something else you're seeing. Are you able to provide any logs or build errors you have to help research this issue?

**Comment by zijiaZ** [comment]
This is the log we saw then app crashes:
And we reverted Branch SDK back to 1.40.1 since that solved this issue
![Screen Shot 2022-09-07 at 4 30 42 PM](https://user-images.githubusercontent.com/81662792/188986127-6de7fc75-63b5-48d2-a910-c754c05785ca.png)

**Comment by echo-branch** [comment]
Could you share what's in General -> Frameworks, Libraries and Embedded Content section of Xcode? Thinking the switch from manual settings to defining in package might have put yours in an odd state.

**Comment by jf-branch** [comment]
Hey @zijiaZ, we're going to close this ticket due to inactivity, please reopen if you are still running into this issue and if you did resolve it, we would love to know the steps taken for resolution.
