### ISSUE TITLE
Test links not resolving when used to launch app

### ISSUE THREAD

**Issue by dustinburke-gh** [BranchMetrics/ios-branch-deep-linking-attribution#1201]
### Describe the bug

When using Branch is Test mode [`Branch.setUseTestBranchKey(true)`] and launching the app from a Branch link opened in Safari, the link does not resolve correctly.

### Steps to reproduce

1. Create a link in the Branch test environment
2. Set your app to useTestBranchKey = true
3. Paste the link in Safari iOS
4. When prompted by iOS to "Open in "[Your App]"?" select "Open"
5. Your app launches

Expected behavior: Branch resolves the link inside this callback:
```
Branch.getInstance().initSession(launchOptions: launchOptions) { (params, error) in
    // code here
}
```

Actual behavior: Branch does not resolve the link and instead in the callback `params` holds this:
key: `+non_branch_link`
value: `my-custom-scheme://open?_branch_referrer={some string}&link_click_id={some string}`

This is my code to set Branch up:

```
Branch.setUseTestBranchKey(true)

if #available(iOS 15, *) {
    Branch.getInstance().checkPasteboardOnInstall()
}

// listener for Branch Deep Link data
Branch.getInstance().initSession(launchOptions: launchOptions) { (params, error) in
    // code here
}
```

### Expected behavior

The link should resolve correctly and have the correct link data attached

### SDK Version

1.41.0

### XCode Version

13.2.1

### Device

iPhone XR

### OS

14.8

### Additional Information/Context

**Note**: This is only happening when `setUseTestBranchKey` is `true` _and_ the link is used to launch the app. If the user launches the app manually and then follows steps 3-5 above when the app is in the background, `params` in the callback block will have the correct values. And none of this is reproducible if using the Live Branch environment.

**Comment by echo-branch** [comment]
Sorry for the late rely, I believe this is an integration issue and should be handled via the support team.
https://help.branch.io/using-branch/page/submit-a-ticket
