### ISSUE TITLE
[1.44.0] Just got blocked in app review because of the Branch SDK

### ISSUE THREAD

**Issue by RamblinWreck77** [BranchMetrics/ios-branch-deep-linking-attribution#1206]
### Describe the bug

Updated to 1.44.0 for a release, and app store review rejected our update demanding to know how we use "Transferable and secure paste functionalities in our app, with an in-app example". We don't use that at all, but I can see copy/paste related changes in 1.44.0 and you're the only integration that changed.

Not happy that we're trying to get a major fix out and got blocked by an integration using special APIs with no warning.

### Steps to reproduce

1. Install 1.44.0
2. send to app review
3. get rejected

### Expected behavior

Don't call special APIs that require review explanations without letting me know

### SDK Version

1.44.0

### XCode Version

14.0

### Device

N/A

### OS

N/A

**Comment by nsingh-branch** [comment]
There were changes in the latest SDK release to support iOS 16's UIPasteControl, so we'll look into this immediately. In the mean time, i would recommend downgrading the Branch SDK to v1.43.2 and trying to resubmit your update if it's urgent.

**Comment by jf-branch** [comment]
@RamblinWreck77 +1 to @nsingh-branch comment, please use 1.43.2. 

For context, Apple introduced new permissions policies with iOS 16.0 in regards to pasteboard access. Branch utilizes the pasteboard for 100% deterministic matching for deep linking on install via our [NativeLink feature](https://branch.io/nativelink/). 

With that, Apple had many bugs on this pasteboard access and a lot of feedback, so they are introducing more changes via 16.1, which was just released. 

 Could you provide additional context as to Apple's messaging? I feel as if an entitlement may be required now.

**Comment by RamblinWreck77** [comment]
Thanks for the explanation! The "feedback" from Apple was very vague, they rejected the binary and sent "Guideline 2.1 - Information Needed"

"please provide details answers to the following questions in your reply to this message in App Store Connect:"

" How does your app integrate the Transferrable and Secure Paste functionalities?"

" Please provide detailed steps on how to locate these features"

and then like 20 paragraphs of app store guidelines boilerplate.

**Comment by jf-branch** [comment]
Thank you @RamblinWreck77! 

We are currently publishing to the app store now to create communications as to why this is occurring. We will keep you posted as to our findings.

**Comment by RamblinWreck77** [comment]
@jf-branch Weird, we don't use those functions at all. Branch was the only SDK that updated between the previous release and that one.

I rolled back the branch SDK and resubmitted the app with no other changes, and it sailed through review.

Maybe this is an Apple/App store review fluke?
