### ISSUE TITLE
The latest Branch SDK 1.45.0 returns an error "SKANErrorDomain Code=10" for each deeplink

### ISSUE THREAD

**Issue by iLabsJason** [BranchMetrics/ios-branch-deep-linking-attribution#1212]
### Describe the bug

Updated to 1.45.0, and then all deeplinks **not** work now, in the `initSession` callback function it returns this error: Error Domain=SKANErrorDomain Code=10 "(null)"

(All deeplinks work fine on the old SDK)

### Steps to reproduce

1. Updated to 1.45.0
2. Click any deeplink
3. print the error in the callback function of `initSession`

### Expected behavior

All deeplinks works fine.

### SDK Version

1.45.0

### XCode Version

14.1

### Device

iPhone XR

### OS

15.5

### Additional Information/Context

Looks the root cause is about this change:
> Added calls to updatePostbackConversionValue on Branch Open events

There are some people have the same issue: https://developer.apple.com/forums/thread/700781

**Comment by jf-branch** [comment]
Hi @iLabsJason, thanks for bringing this to our attention, we will look into this.

**Comment by jf-branch** [comment]
@iLabsJason, thank you for notifying us of this issue, we have released 1.45.1 that fixes this.
