### ISSUE TITLE
Release 1.45.1 breaks deeplinks

### ISSUE THREAD

**Issue by lilidotshi** [BranchMetrics/ios-branch-deep-linking-attribution#1214]
### Describe the bug

Testing on iOS 15.4, iPhone 12. After updating from 1.45.0 to 1.45.1, deeplinks for our app are no longer working.

### Steps to reproduce

1. Upgrade to 1.45.1
2. Test any deeplink to an app using Branch
3. Observe that the `registerDeepLinkHandler` completion handler is never called

### Expected behavior

I expect `registerDeepLinkHandler` to get called and deeplink to be handled

### SDK Version

1.45.1

### XCode Version

14.1

### Device

iPhone 12

### OS

15.4

### Additional Information/Context

I suspect that the changes made to BranchOpenRequest.m or BranchEvent.m broke something, as the logic for calling the completion blocks are not entirely equal between versions 1.45.1 and 1.45.0, eg: The completion blocks are now being called in the sequential logic, and not in the completion handler supplied to the `BNCSKAdNetwork.updatePostbackConversionValue` function. 

If it also helps: iOS 16.1 works just fine.

**Comment by lilidotshi** [comment]
I am also able to verify that rolling back to version 1.45.0 makes the links work again.

**Comment by jf-branch** [comment]
Hi @lilidotshi! 

Thanks for bringing this to our attention we were able to reproduce and resolved it with our release last night of[ 1.45.2 ](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/1.45.2)

Pleas reopen if this continues to occur for you even on 1.45.2
