### ISSUE TITLE
Branch crash on macCatalyst on skAdNetworkUpdatePostbackConversionValueCoarseValueLockWindow

### ISSUE THREAD

**Issue by sergiocampama** [BranchMetrics/ios-branch-deep-linking-attribution#1218]
### Describe the bug

The new API for `skAdNetworkUpdatePostback:coarseValue:lockWindow` is properly guarded for iOS 16.1, but it's not guarded for macCatalyst 16.1, so Copilot macOS app crashes on users that are on macOS 13.0. Could this guard be added to the check in line 108 of file `BNCSKAdNetwork.m`?

### Steps to reproduce

1. Integrate pod Branch at version 1.45.2
2. Use on a catalyst app on macOS 13.0
3. Invoke the skAdNetworkUpdatePostbackConversionValueCoarseValueLockWindow call

### Expected behavior

To not crash.

### SDK Version

1.45.2

### XCode Version

14.0, but irrelevant

### Device

macOS

### OS

13.0

**Comment by sergiocampama** [comment]
btw, if you use `API_DEPRECATED("This is no longer supported for iOS 16.1+ - SKAN4.0", ios(13.0, 16.0), macCatalyst(13.0, 16.0))` instead to deprecate APIs, clients will be able to better guard those calls resulting in less build warnings

**Comment by echo-branch** [comment]
@sergiocampama 
Thanks for the heads up, we'll work to get this into the next patch.

**Comment by echo-branch** [comment]
This should be fixed in 2.1.2
