### ISSUE TITLE
Try to open several apps

### ISSUE THREAD

**Issue by and7ey** [BranchMetrics/ios-branch-deep-linking-attribution#1226]
### Describe the feature

Will branch.io can help me to implement the following functionality:

1. I have multiple iOS applications (let's say, app1, app2 and app3)
2. Each application has its own deeplinks (for ex., app1://, app2:// and app3://)
3. Each application has its own universal links (something.app1.com, anything.app2.com, example.app3.com)

App1 and App2 are already deleted from the App Store, their update is not possible.

I would like to send to multiple users a single SMS (with **one** URL, with no user id), which will lead user to the application (it could be app3, app2 or app1 - whatever is installed).

**Comment by jf-branch** [comment]
Hi @and7ey, I would strongly suggest to open up a support ticket via: https://help.branch.io/using-branch/page/submit-a-ticket and they will be able to help answer your question.

**Comment by and7ey** [comment]
Am I supposed to be your customer to get an answer there?
The webpage shows me just the header, `submit a ticket` does nothing.

**Comment by jf-branch** [comment]
<img width="972" alt="Screen Shot 2023-02-09 at 10 20 26 AM" src="https://user-images.githubusercontent.com/61431395/217854815-c2e3257c-d6f0-45cf-95bb-98bac08a826d.png">
Are you not seeing this page?

**Comment by and7ey** [comment]
I haven't seen it before, but checked from another device and it is there. Thanks for your help, I will ask for support there.

**Comment by echo-branch** [comment]
Likely an integration issue and rerouted to support team.
