### ISSUE TITLE
Pod hash changed for an existing version

### ISSUE THREAD

**Issue by gsbernstein** [BranchMetrics/ios-branch-deep-linking-attribution#1228]
### Describe the bug

The pod hash changed for existing releases. Assuming this is intentional and not malicious, this is very bad practice for security and reliability.

### Steps to reproduce

1. run `pod install` on an existing integration (in our case version 1.41.0)

expected: should succeed with existing hash `bd6c472d6cab03206877ac86c1241327a3f217d1`
actual: integration builds fail due to hash not matching, now `5b53e039f5d5cdd12dc5d34b1a6b165168cab9d2`

### Expected behavior

should succeed with existing hash

### SDK Version

1.41.0

### XCode Version

14.2 (14C18)

### Device

n/a

### OS

n/a

**Comment by dingwilson** [comment]
+1 noticed as well. Can we get an explanation from Branch team about this?

**Comment by youknowhu** [comment]
I'm running into the same issue -- this is breaking our iOS builds and deploys because of the checksum from installing Branch (on SDK version 1.39.2)

**Comment by echo-branch** [comment]
Thanks for the heads up. I was trying to put in a notification that the Branch pod was renamed to BranchSDK, but it seems I messed it up. Looking into it now.

**Comment by echo-branch** [comment]
Does the problem resolve with `pod update`? 
How about removing the `Podfile.lock` and `Pods` folder then reinstalling?

I'm not certain I can easily roll this back as it appears to be the way cocoapods implemented the `pod trunk deprecate NAME --in-favor-of=OTHER_NAME` command. It appears to modify the podspec with a notice which would change the hash.

**Comment by youknowhu** [comment]
I ran a `pod update` which updated the version from 1.39.2 to 1.39.4, which fixed the issue for me.

**Comment by fossage** [comment]
Yea, looks like the issue has to do with [these commits](https://github.com/CocoaPods/Specs/commits?author=echo-branch) which added a `deprecated_in_favor_of` field to the Podspecs for a bunch of the older SDKs which ended up changing the hash value for the Pod in Podfile.lock.

**Comment by echo-branch** [comment]
Looks like we're not going to be able to fix this as it is an unfortunate design choice by Cocoapods. Workaround is to ignore the warning and just remove the lock and `pod update`.

**Comment by gsbernstein** [comment]
Weird implementation choice from cocoapods, but thank you for taking it seriously and investigating.
