### ISSUE TITLE
Why the entitlement file is needed during Copy Bundle Resources build phase ?

### ISSUE THREAD

**Issue by xseignard** [BranchMetrics/ios-branch-deep-linking-attribution#1230]
### Describe the bug

Hello
According to your docs: https://help.branch.io/developers-hub/docs/ios-basic-integration#4-configure-entitlements
And looking at Branch-TestBed: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-TestBed/Branch-TestBed.xcodeproj/project.pbxproj#L1350

It seems that we need to add the entitlement to the Copy Bundle Resources build phase.

But this shouldn't be necessary as it is "an input to the code signing machinery. Once you’ve built your app, the entitlements are baked into the code signature" (quoting from [there](https://developer.apple.com/forums/thread/701617))

Can you explain why we need this file in the final bundle?

### Steps to reproduce

N/A

### Expected behavior

Same behavior without the `entitlements` file in the final bundle.

### SDK Version

All

### XCode Version

N/A

### Device

N/A

### OS

N/A

**Comment by echo-branch** [comment]
@xseignard 
It's describing legacy Xcode behavior. If you're working on an app created in an older version of Xcode you'll see that layout.

Nowadays Xcode does not include the entitlements like that. It also doesn't generate an Info.plist. I'll add this to the list of things we need to clarify for the current Xcode.

**Comment by xseignard** [comment]
Thanks for the clarification! 🙏
