### ISSUE TITLE
Query parameter is not extracting & user activity method is not getting called

### ISSUE THREAD

**Issue by nickp4488** [BranchMetrics/ios-branch-deep-linking-attribution#1257]
### Describe the bug

Hello,
Reference: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1057

This issue is still persists & also user continue activity method is not getting called when deeplinking happen.

Please provide the solution for this!
Thank you,

### Steps to reproduce

1.
2.
3.

### Expected behavior

call user activity method in app delegate.

### SDK Version

2.1.2

### XCode Version

14.3

### Device

iPhone 12

### OS

16.5

**Comment by echo-branch** [comment]
@nickp4488 
I believe you're running into an integration issue. We're trying to move those types of issues over to our support team. https://help.branch.io/using-branch/page/submit-a-ticket

The previous ticket included more than one integration issue. But to summarize.

1. Did you implement all the lifecycle hooks? It will vary a bit depending on how you implemented your app. https://help.branch.io/developers-hub/docs/ios-basic-integration
2. Is Branch init in a race with the lifecycle calls? Init must occur prior to the lifecycle calls, so if you delay init we will not get the lifecycle call. If you must delay, cache the lifecycle call and pass it along when you're ready.
3. Branch only provides payload data for links that have data on the servers. Hand crafting a link with params, will result in a no.
4. Are you attempting to call Branch prior to init? This will result in an error scenario where the recovery process may miss the first lifecycle call. Note this can occur if an event call is done async and it races your Branch init call.

**Comment by JagadeeshKaricherla-branch** [comment]
Asked the reporter to open a support ticket.
