### ISSUE TITLE
Breaking Change moving from 2.1.2 to 2.2.0

### ISSUE THREAD

**Issue by farmer-dhi** [BranchMetrics/ios-branch-deep-linking-attribution#1265]
### Describe the bug

Version 2.1.2 has the method `delayInitToCheckForSearchAds()` which was removed in 2.2.0. This has broken my build, and it's not clear what I should replace it with (if anything).

### Steps to reproduce

1. Create a new project and install Branch v2.1.2
2. use the method delayInitToCheckForSearchAds()
3. Update to Branch v2.2.0
4. Attempt to build project

EXPECTED: Build succeeds
ACTUAL: Build fails

### Expected behavior

I expected a non-major version change to allow my project to build without needing changes from me.

### SDK Version

2.2.0

### XCode Version

14.3

### Device

Simulator

### OS

16.4

**Comment by jf-branch** [comment]
Hi @farmer-dhi, the Apple API that delay check was used for has been deprecated and therefore the delay is no longer needed. You can remove that line of code.

**Comment by farmer-dhi** [comment]
Thank you, I will do so :)

**Comment by sfoulston** [comment]
Just found this as well - it would be great if the explanation / migration notes for breaking changes like this could be documented in the release notes 🙏
