### ISSUE TITLE
`Branch.setTrackingDisabled` vs Privacy Manifest

### ISSUE THREAD

**Issue by lpikorhcp** [BranchMetrics/ios-branch-deep-linking-attribution#1322]
### Describe the bug

I updated the Branch SDK to version `3.0.0`. Within the project we use `Branch.setTrackingDisabled(true)` method to disable tracking. However, when archiving the app and then generating a privacy report it says that the app is using:

- Device ID for Third-Party Advertising, Developer's Advertising or Marketing and Analytics with Tracking set to `YES`.

If I understand correctly how `setTrackingDisabled` method works, this is not true, and so `Tracking` should be set to `NO` in a privacy report document.

Can this be somehow achieved, given that the privacy report is generated based on `plist` files? I'm afraid that this may negatively impact the App Store review process for apps that currently don't track users and have tracking disabled set to true. 

### Steps to reproduce

1. Update Branch SDK to version `3.0.0`
2. Use `Branch.setTrackingDisabled(true)` within your project
3. Archive & export privacy report.

### Expected behavior

Tracking should be set to `NO`.

### SDK Version

3.0.0

### Xcode Version

15.0

### Device

iPhone 15

### OS

iOS 17

**Comment by echo-branch** [comment]
@lpikorhcp 
Thanks for pointing this out. Our privacy manifest is not dynamically generated, so the list of collected data is based on apps that do opt into ads measurement and linking. For those only using linking, there are a lot of items that would never be collected. I'm gonna open a ticket to research what can be done about this.

**Comment by lpikorhcp** [comment]
Thank you @echo-branch for taking a look at this. While editing `PrivacyInfo.xcprivacy` sounds interesting, for now I'll leave it as a last resort - our release process is automated and Branch SDK is not committed into our repo, so editing plist file would have to be scripted.

**Comment by lpikorhcp** [comment]
This issue is still valid.

**Comment by LydGol90** [comment]
Hi, yes facing this issue as well. We only use the SDK for deeplinking and so the Privacy Manifest is not relevant for us. Currently this SDK is the only reason our app would require this label. Is it better for the default manifest to not include these and then developers can add it to their own manifests as needed? With something in the documentation to alert developers that they need to do it. Many thanks
