### ISSUE TITLE
Support visionOS compilation

### ISSUE THREAD

**Issue by gutenbergn** [BranchMetrics/ios-branch-deep-linking-attribution#1357]
### Describe the feature

Right now the SDK does not compile when targeting visionOS. The issues are with the usage of `keyWindow` in `UIViewController+Branch.m` as well as with fetching the `SKProduct` `contentVersion` in `BranchEvent.m`.

Any plans to support that?

**Comment by echo-branch** [comment]
@gutenbergn 
We have an internal ticket for this as well. Although we don't plan on full visionOS support, we will try to make sure the SDK will at least compile and the core feature set works on simulator.

**Comment by MikesHorcrux** [comment]
@echo-branch  Is there an eta on when this will be available?
