### ISSUE TITLE
Failure to get callbacks when upgrading from 3.0.0 to 3.3.0

### ISSUE THREAD

**Issue by Splash04** [BranchMetrics/ios-branch-deep-linking-attribution#1364]
### Describe the bug

Faced with issue after updating SDK version.
Old app contains SDK v3.0.0; new app version: v3.3.0.

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        Branch.setUseTestBranchKey(true)
        Branch.getInstance().initSession(launchOptions: launchOptions, automaticallyDisplayDeepLinkController: false, deepLinkHandler: handleDeepLink)
}

func handleDeepLink(params: [AnyHashable: Any]?, error: Error?) {}
```
The main issue:
**After app update, deepLinkHandler is never called. App restart not help.
The only solution is to delete app and install from scratch. But such case is NOT acceptable for app users.**

`Network finish operation https://api3.branch.io/v1/open 0.944s. Status 200 error (null).`

Expected result: deepLinkHandler call just after app launch.

- Not sure about behavior with TestBranch == false. I had added additional logs to track this issue on prod.
- I had 1 simulator (iOS 17.2) and 2 devices (13 pro 15.7.1; 12 pro max 16.7.2) that have the same issue after first update. 
- But I'm not able to reproduce this issue on the same device a second time. Those.: Faced with issue -> remove the app -> install app version with SDK 3.0.0 and run -> Install App with SDK 3.3.0 and run -> All looks good. Maybe I need to use an app for some time, or receive some link before updating to reproduce the issue.

Log file:
[Branch_io_log.txt](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/files/14514854/Branch_io_log.txt)

The same issue as users described here:
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/760#issuecomment-1640572758
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/914#issue-434226742
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/532#issue-554558963
And a lot of threads at stackoverflow.

### Steps to reproduce

1.
2.
3.

### Expected behavior

deepLinkHandler call after app launch.

### SDK Version

3.3.0

### XCode Version

15.2

### Device

iPhone 13 pro

### OS

15.7.1

**Comment by Splash04** [comment]
<img width="1249" alt="Screenshot 2024-03-07 at 00 01 40" src="https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/f038c704-fde2-4bb0-a062-1332af771ec9">
<img width="1601" alt="Screenshot 2024-03-06 at 23 57 02" src="https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/6057ba94-1448-48f0-ad12-02f3234e31e0">


Well, looks like SDK on findExistingInstallOrOpen take BranchOpenRequest with empty callback.
And at the same time urlString is nil as well, so **if** and **else** cases just NOT save initSessionCallback and we lose it

**Comment by echo-branch** [comment]
@Splash04 
Mind opening a support ticket for this? The upgrade scenario should work.

Now the status 200, is actually the http status which is ok. That's just informational and not an error. So I'm going to rename this ticket to correctly describe it as a potential upgrade issue.

**Comment by echo-branch** [comment]
Looking at the logs and screenshots, the behavior is as expected. So I think a deeper analysis is necessary.

The else block is to handle a very specific lifecycle situation. Most of the time we actually do NOT want to create a new request. The reason it exists is if we have two lifecycle events come in very rapidly and the second lifecycle has link data, we cannot ignore like we normally do. We must make an attempt to resolve that one as well.

**Comment by Splash04** [comment]
I'm still have one phone with this issue. So I will try to provide some additional details that maybe help:

1. On App launch be some reason we load for file "BNCServerRequestQueue" just one BranchOpenRequest with empty field:
![empty_request](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/ef3d38c6-eca8-459c-bb9a-0e2dddc4c6ac)

2. Init branch single with this data:
![init_branch_singletone](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/4bdaaba8-dc86-4118-8401-b93614471279)

3. Checking request [self.requestQueue findExistingInstallOrOpen] and not saving initSessionCallback:
![checking_request_in_queue](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/9de027f1-42a6-41cb-b762-353c403f642b)

4. Processing empty BranchOpenRequest:
![processing_empty_request_from_queue](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/d820425a-edc2-4331-84f3-edfc26a22d38)

5. Send open event to server:
![send_open_event_to_server](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/b6679c07-fef3-4fe9-8ca4-dcb4a0a1fae6)

6. on processResponse we don't have errors and callback is null, so just load data and [BranchOpenRequest releaseOpenResponseLock]
![releaseOpenResponseLock](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/473444b5-aad0-4ba9-8723-fa07b77f9f13)

7. Callback null, so do nothing here:
![empty_callback](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/29d95239-42c6-422f-936a-f4e1d6a54c86)

8. processNextQueueItem 
![processNextQueueItem](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/b965096f-905e-4310-a8f1-1c4abcf6ef19)

So no callback call here.

When I compare this flow with clear setup flow, I had seen that  findExistingInstallOrOpen don't return anything.
So we're creating BranchOpenRequest and saving initSessionCallback. And initSessionCallback call after the end.
![fresh_install](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/c358d445-8288-4f37-8186-350c360b2bec)

**Comment by Splash04** [comment]
For developers who faced with this issue. This actions should help.

1. We should create timer to catch BranchIO freeze and force start the app. I had selected 15 sec timeout.
2. We should clear the cache file for branch serverRequestQueue to avoid freeze on the next launch.

```
@main
class AppDelegate: UIResponder, UIApplicationDelegate {

    private var branchIOLaunchTimer: Timer?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    	// code
    	startBranchTimeoutTimer()
    	Branch.getInstance().initSession(launchOptions: launchOptions, automaticallyDisplayDeepLinkController: false, deepLinkHandler: handleDeepLink)
    }

    func handleDeepLink(params: [AnyHashable: Any]?, error: Error?) {
    	stopBranchTimeoutTimer()
    	// handle DeepLink
    }
}

// ******************************* MARK: - Branch iOS workaround

extension AppDelegate {
	@objc
    private func onBranchTimerTimeout() {
        logError("Branch IO app launch Timeout")
        // Just additional safety (Queue should be already empty), basically do nothing for our issue
        Branch.getInstance().clearNetworkQueue()
        
        /*
         The main issue, that file for serverRequestQueue cache contains invalid event
         so we need to get path to this file and clear it
         */
        
        /* persistImmediately will not clean up the file, because it contains checking count != 0
            if let serverRequestQueue = (BranchSDK.BNCServerRequestQueue.getInstance() as? BranchSDK.BNCServerRequestQueue) {
                print("serverRequestQueue: \(serverRequestQueue.queueDepth())")
                serverRequestQueue.persistImmediately()
            }
         */
        
        // Load serverRequestQueue file path from ObjecitiveC code
        if let fileUrl = ObjectiveCUtils.serverRequestQueueURL() {
            logDebug("Remove cache file for branch serverRequestQueue", data: ["fileUrl" : fileUrl])
            removeFile(fileUrl: fileUrl)
        }
        
        // Force start the app
        handleDeepLink(params: [:], error: nil)
    }
    
    func removeFile(fileUrl: URL) {
        if FileManager.default.fileExists(atPath: fileUrl.path) {
            do {
                try FileManager.default.removeItem(atPath: fileUrl.path)
                print("File deleted: \(fileUrl)")
            } catch {
                print("Could not delete file, probably read-only filesystem")
            }
        } else {
            print("File not exist")
        }
    }
    
    fileprivate func startBranchTimeoutTimer() {
        if let _ = self.branchIOLaunchTimer { return }
        self.branchIOLaunchTimer = Timer.scheduledTimer(timeInterval: 10.0,
                                                        target: self,
                                                        selector: #selector(onBranchTimerTimeout),
                                                        userInfo: nil,
                                                        repeats: false)
    }
    
    private func stopBranchTimeoutTimer() {
        self.branchIOLaunchTimer?.invalidate()
        self.branchIOLaunchTimer = nil
    }
}
```

The main problem here that serverRequestQueue cache file path is a private method in objectiveC class. So, we have to use Objective-C Runtime Utilities function to get selector by name ([NSSelectorFromString](https://developer.apple.com/documentation/foundation/1395294-nsselectorfromstring)). Please, check that function name is not changed:
![function_name](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/4971909/d21ee0b7-eee1-4a34-8d84-bba0098a21ef)

How to get this path:
1. Create ObjectiveCUtils.h:
```
#import <Foundation/Foundation.h>

@interface ObjectiveCUtils : NSObject

+ (NSURL *) serverRequestQueueURL;

@end
```
2. Accept to create -Bridging-Header.h when XCode asks you. It should contain just one line:
`#import "ObjectiveCUtils.h"`
3. Create ObjectiveCUtils.m
```
#import "ObjectiveCUtils.h"
#import "Branch.h"

@implementation ObjectiveCUtils

+ (NSURL *) serverRequestQueueURL {
    SEL privateSelector = NSSelectorFromString(@"URLForQueueFile");
    if ([BNCServerRequestQueue respondsToSelector: privateSelector]) {
        id url = [BNCServerRequestQueue performSelector: privateSelector];
        
        if ([url isKindOfClass: [NSURL class]]) {
            return url;
        } else {
            printf("Invalid class type for URLForQueueFile url\n");
            return NULL;
        }
    } else {
        printf("Selector for URLForQueueFile is not found\n");
    }
    
    return NULL;
}

@end
```

**Comment by echo-branch** [comment]
@Splash04 
Thanks for the detailed logs and your workaround. Looking to see if I can reproduce this on my own test devices. 
Either way, I think an additional safety check for invalid events in storage is necessary in the next patch.

**Comment by echo-branch** [comment]
A error recovery safety check similar to the one described here was added in the latest release. 
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/3.4.1

**Comment by jshiv2023** [comment]
can any one helped me to integrate branch.io in ios for react native.. 
I had tried it with multiple times but still not getting what is the issues ?
