### ISSUE TITLE
Apple privacy manifest not working

### ISSUE THREAD

**Issue by ritrashin2** [BranchMetrics/ios-branch-deep-linking-attribution#1375]
### Describe the feature

I am importing branch sdk through cocoapods.

Import BranchSDK, there will be a conflict with my project's privacyinfo file, and if you remove privacyInfo from my project and build it, branchsdk will not shown in the privacy manifest report.

Looking at the screenshots, you can see the following differences:

![branch_](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/53362163/56cf3d79-de8b-442d-b64a-4761bdc8f325)
![firebase_](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/assets/53362163/a3a2bef3-ea29-4f53-95c6-77667767fd5b)

I found the difference in **podspec** through this page https://forums.developer.apple.com/forums/thread/745546.

BranchSDK
```
   s.resource = "Sources/Resources/PrivacyInfo.xcprivacy"
```
It is specified as

Other SDKs have **PrivacyInfo.xcprivacy** set in **resource_bundles** with the target name.

**Comment by echo-branch** [comment]
This should be fixed in the latest release.
