### ISSUE TITLE
initSessionWithLaunchOptions callback being called twice

### ISSUE THREAD

**Issue by pyettra** [BranchMetrics/ios-branch-deep-linking-attribution#1404]
### Describe the bug

Hello! Something very odd happing while calling initSessionWithLaunchOptions:
`- (void)initSessionWithLaunchOptions:(NSDictionary *)options andRegisterDeepLinkHandler:(callbackWithParams)callback { [self initSessionWithLaunchOptions:options isReferrable:YES explicitlyRequestedReferrable:NO automaticallyDisplayController:NO registerDeepLinkHandler:callback]; }`

Whenever I try to open a branch link, the callback is being called twice. This happens if I have the app open on background or not. Right now, it's not having effects on the way I receive the branch link params, but the doubled calls are causing side effects on my UI.

### Steps to reproduce

1. add a debugger on initSessionWithLaunchOptions
2. click on a branch link
3. see initSessionWithLaunchOptions callback being called twice

### Expected behavior

The initSessionWithLaunchOptions should only be called once

### SDK Version

3.4.3

### XCode Version

15.1

### Device

iPhone 15 Plus

### OS

15.0

**Comment by sleepygarden** [comment]
Bump, I'm also encountering this issue
