### ISSUE TITLE
The function getShortUrlWithLinkProperties giving wrong url

### ISSUE THREAD

**Issue by gupta-manish** [BranchMetrics/ios-branch-deep-linking-attribution#907]
Hi,

So my applink is adobepsx.app.link.

But getShortUrlWithLinkProperties function is generating adobe-psx.app.link. 

As a result the link is not deep linking to the application.

**Comment by csalmi-branch** [comment]
@gupta-manish What version of the SDK and iOS are you using?

**Comment by csalmi-branch** [comment]
@gupta-manish Are you still having this issue?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
