### ISSUE TITLE
The meta data is not retrieved occasionally.

### ISSUE THREAD

**Issue by touren** [BranchMetrics/ios-branch-deep-linking-attribution#912]
XCode 10.1
Swift 4.2
Branch 0.26.0

**Most of the time, we got the correct meta data:**

> 2019-04-08 14:22:01.220178-0400 ElsewhereQA[7010:728899] [branch.io] BNCNetworkService.m(232) Debug: Network start operation https://api2.branch.io/v1/open.
> 
> 2019-04-08 14:22:02.043344-0400 ElsewhereQA[7010:728823] [branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api2.branch.io/v1/open 0.869s. Status 200 error (null).
> 
> {"session_id":"643865489470395470","identity_id":"615250201904808852","link":"https://wcv8.app.link?%24identity_id=615250201904808852","data":"{\"$og_title\":\"JK Rowling\",\"~creation_source\":3,\"$og_description\":\"Video created with Elsewhere. Open the app to make your own!\",\"+click_timestamp\":1554747721,\"$identity_id\":615250201904808852,\"$og_image_url\":\"https://d7lkuqq27li9i.cloudfront.net/uploads/video_package/thumbnail/613/thumbnail.png\",\"~feature\":\"sharing\",\"+match_guaranteed\":true,\"$canonical_identifier\":\"613\",\"+clicked_branch_link\":true,\"variation_id\":\"705023b1-478c-4ca4-af7c-d9d8230661b9\",\"$one_time_use\":false,\"~id\":643846345475754364,\"+is_first_session\":false,\"~referring_link\":\"https://wcv8.app.link/8MROg8bZIV\"}","device_fingerprint_id":"613803230103076340"}.
> 
> 2019-04-08 14:22:02.043454-0400 ElsewhereQA[7010:728823] [branch.io] BNCServerInterface.m(822) Debug: Server returned: Status: 200; Data: {
> 
>    data = "{\"$og_title\":\"JK Rowling\",\"~creation_source\":3,\"$og_description\":\"Video created with Elsewhere. Open the app to make your own!\",\"+click_timestamp\":1554747721,\"$identity_id\":615250201904808852,\"$og_image_url\":\"https://d7lkuqq27li9i.cloudfront.net/uploads/video_package/thumbnail/613/thumbnail.png\",\"~feature\":\"sharing\",\"+match_guaranteed\":true,\"$canonical_identifier\":\"613\",\"+clicked_branch_link\":true,\"variation_id\":\"705023b1-478c-4ca4-af7c-d9d8230661b9\",\"$one_time_use\":false,\"~id\":643846345475754364,\"+is_first_session\":false,\"~referring_link\":\"https://wcv8.app.link/8MROg8bZIV\"}";
> 
>    "device_fingerprint_id" = 613803230103076340;
> 
>    "identity_id" = 615250201904808852;
> 
>    link = "https://wcv8.app.link?%24identity_id=615250201904808852";
> 
>    "session_id" = 643865489470395470;
> 
> }. 
> 

**But sometimes, the server returns "+non_branch_link" for the same link, https://wcv8.app.link/8MROg8bZIV**

> 2019-04-08 14:18:01.729061-0400 ElsewhereQA[7010:728324] [branch.io] BNCNetworkService.m(232) Debug: Network start operation https://api2.branch.io/v1/open.
> 
> 2019-04-08 14:18:06.602104-0400 ElsewhereQA[7010:728320] [branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api2.branch.io/v1/open 4.903s. Status 200 error (null).
> 
> {"session_id":"643864494585517479","identity_id":"615250201904808852","data":"{\"+non_branch_link\":\"https://wcv8.app.link/8MROg8bZIV\",\"+clicked_branch_link\":false,\"+is_first_session\":false}","device_fingerprint_id":"613803230103076340"}.
> 
> 2019-04-08 14:18:06.602288-0400 ElsewhereQA[7010:728320] [branch.io] BNCServerInterface.m(822) Debug: Server returned: Status: 200; Data: {
> 
>     data = "{\"+non_branch_link\":\"https://wcv8.app.link/8MROg8bZIV\",\"+clicked_branch_link\":false,\"+is_first_session\":false}";
> 
>     "device_fingerprint_id" = 613803230103076340;
> 
>     "identity_id" = 615250201904808852;
> 
>     "session_id" = 643864494585517479;
> 
> }.
> 
> 2019-04-08 14:18:06.617314-0400 ElsewhereQA[7010:728239] [Crashlytics:Crash] WARNING: CLSLog has been used before (or concurrently with) Crashlytics initialization and cannot be recorded. The message was: 
> 
> params: ["+non_branch_link": https://wcv8.app.link/8MROg8bZIV, "+clicked_branch_link": 0, "+is_first_session": 0]
>

**Comment by csalmi-branch** [comment]
@touren are you still experiencing this issue?

**Comment by echo-branch** [comment]
Closing due to no response from reporter
