### ISSUE TITLE
Not redirecting to url because of https://api2.branch.io/v1/open, Status 200 error

### ISSUE THREAD

**Issue by github-prathma** [BranchMetrics/ios-branch-deep-linking-attribution#914]
If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by github-prathma** [comment]
Debug: Network finish operation https://api2.branch.io/v1/open 0.643s. Status 200 error (null).
{"session_id":"647018792144274324","identity_id":"647006397716155849","link":"https://bnc.lt/a/key_live_ofpAFmyUCF2nyYtmXjmk1fefgfjDU62v?%24identity_id=647006397716155849","data":"{\"+non_branch_link\":\"https://curofy.com/news/51528-ShortNews--Air-pollution-is-killing-more-people-in-India-than-smoking?utm_source=paid&utm_campaign=air-pollution&utm_medium=Facebook&_branch_match_id=393621824009718200\",\"+clicked_branch_link\":false,\"+is_first_session\":false}","device_fingerprint_id":"647006397703503553"}.
2019-04-17 16:42:07.813038+0530 Curofy[7966:2568280] [branch.io] BNCServerInterface.m(822) Debug: Server returned: Status: 200; Data: {
    data = "{\"+non_branch_link\":\"https://curofy.com/news/51528-ShortNews--Air-pollution-is-killing-more-people-in-India-than-smoking?utm_source=paid&utm_campaign=air-pollution&utm_medium=Facebook&_branch_match_id=393621824009718200\",\"+clicked_branch_link\":false,\"+is_first_session\":false}";
    "device_fingerprint_id" = 647006397703503553;
    "identity_id" = 647006397716155849;
    link = "https://bnc.lt/a/key_live_ofpAFmyUCF2nyYtmXjmk1fefgfjDU62v?%24identity_id=647006397716155849";
    "session_id" = 647018792144274324;
}.
2019-04-17 16:42:07.825918+0530 Curofy[7966:2568280] [branch.io] BranchOpenRequest.m(328) DebugSDK: Resuming openRequestWaitQueue.

bnc link is sometimes opening and sometimes not. Correct url params are not retrieving because of BNCNetworkInterface "Network finish operation" error. Sometimes api2.branch.io/v1/close or api2.branch.io/v1/open gives error as Status 200. And sometimes when BNCNetworkInterface connects successfully, it redirects to url correctly otherwise it just opens the app with main screen.

Does anyone know the fix so that bnc link always redirect to correct url? I am using bnc.lt as domain for link

**Comment by csalmi-branch** [comment]
@github-prathma have you tried following the instructions here? https://docs.branch.io/apps/android/#using-bnclt-or-a-custom-link-domain

If so, can you provide us some more information about your configuration?

**Comment by csalmi-branch** [comment]
@github-prathma have you tried following the instructions here? https://docs.branch.io/apps/ios/#enable-100-matching

If so, can you provide us some more information about your configuration?

**Comment by echo-branch** [comment]
Closing due to no response from reporter
