### ISSUE TITLE
Paste link to safari and jump, then open the app, still get the link data and has to handle it

### ISSUE THREAD

**Issue by tango5614** [BranchMetrics/ios-branch-deep-linking-attribution#915]
I Integrated IOS SDK like your document says, handle link's data in `Branch.getInstance().initSession`'s callback
The question is:
When I generate a link which will cause my app navigating a certain page, copy it to safari then jump, it fallback to the $fallbackurl, which is OK.
But when I reopen my app, `Branch.getInstance().initSession`'s callback is called.I still can get the link's data.Thus my app has to handle it and nav to that page, which I don't want to.

Is there any way to stop my app rehandling the link's data, since users have already seen the page in safari.

**Comment by derrick-branch** [comment]
Hi @tango5614, can you write into support@branch.io if you want to explore this further? There is currently no way to know in-app whether the user went through the $fallback_url. This would be a feature request, and unfortunately I don't think it is an easy one. Sorry for the inconvenience.
