### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by gabrielPeart** [BranchMetrics/ios-branch-deep-linking-attribution#928]
At WWDC 2019, Apple announced Xcode integration with Swift Package Manager. It would be great to be able to use it with your library.

If you have doubts, please, check the following links:

[How to use](https://developer.apple.com/videos/play/wwdc2019/408/)

[Creating Swift Packages](https://developer.apple.com/videos/play/wwdc2019/410/)

**Comment by echo-branch** [comment]
We have a backlogged ticket for this one.

**Comment by bogartpi** [comment]
Would be great to use Branch with Swift Package Manager!

**Comment by bdrelling** [comment]
Is there any status update for this @echo-branch (or other maintainers)?

**Comment by echo-branch** [comment]
It's still in our backlog.  Hoping to get it next sprint.

**Comment by bdrelling** [comment]
@echo-branch Awesome, thank you for the update!

**Comment by RamblinWreck77** [comment]
+1, would love this! We had recently migrated to 100% SPM fully had to go back to hybrid SPM/Cocoapods to setup branch.

**Comment by bdrelling** [comment]
@echo-branch can I ping for another update? We're just trying to track this so we can finish the conversion to SPM, sorry to hassle you. Hope you don't have 6 week sprints! 😬

**Comment by echo-branch** [comment]
@bdrelling Oh man, sometimes it feels like 6 week sprints.  I'm currently rotating across multiple platforms, so iOS is getting released less frequently than I'd like.  It's more like every 2 or 3 sprints rather than every sprint.  

Next sprint is React Native and Cordova, after that I hope to get this one for iOS.

**Comment by bdrelling** [comment]
@echo-branch thanks for the context!

**Comment by echo-branch** [comment]
Quick update.  This is taking longer than expected due to unconventional project layout.

**Comment by bdrelling** [comment]
@echo-branch Thanks for the previous update. Any luck with this recently? Thanks!

**Comment by luismmejiasb** [comment]
Hi @echo-branch  hope you're doing well. Is there any update for 2020 :)

**Comment by echo-branch** [comment]
@luismmejiasb 
Unfortunately, I'm working on resolving critical issues for our React Native users.  Hopefully I can return to work on iOS afterwards.

**Comment by JonathanDowning** [comment]
Thanks for the update!

**Comment by twalshcbs** [comment]
Can you look at working on this again?  Maybe making another branch for non-React Native users.

**Comment by echo-branch** [comment]
@twalshcbs This is on our backlog.  We need to make some changes for Catalyst support which is tangentially related, so hopefully we can get both onto one of the next couple sprints.

**Comment by MihaelIsaev** [comment]
I've implemented SPM support in [my fork](https://github.com/MihaelIsaev/ios-branch-deep-linking-attribution) but the whole repo is about ~620Mb and it takes a lot of time to add it into SPM. I think it is because of `framework` files commited for Carthage.

Since this repo is `MIT` licensed I copied SDK's source files and created a [new clean lightweight repo with SPM support](https://github.com/MihaelIsaev/branch.io.spm).

**Comment by OhItsShaun** [comment]
Throwing a +1 behind this; we're gradually moving away from CocoaPods to SwiftPM, and Branch is one of our remaining holdouts.

**Comment by RGG-jayoung** [comment]
Throwing a +1 behind this as well. Branch is a SPM holdout for us as well.

**Comment by makoni** [comment]
+1

**Comment by JonathanDowning** [comment]
+1!

**Comment by MaxDesiatov** [comment]
Hi @echo-branch, would there be any updates on this before Xcode 12 is released? I imagine it would be great to start implementing and testing this now, so that if any bugs are discovered they can be reported to Apple and hopefully fixed before Xcode 12 GM is out.

**Comment by david1hyman** [comment]
I had a whole project with no pods... then Branch. Hook it up thx.
+1!

**Comment by bdrelling** [comment]
Looking for an update on this as we’re blocked from a full migration over to SPM. 

@echo-branch (or anyone else), any news for us? Thanks!

**Comment by echo-branch** [comment]
@bdrelling 
It's merged to staging and will be included with our next release.  

Note that it only supports iOS and not tvOS though.  We need to restructure a few classes to make SPM support for tvOS work properly.

**Comment by bdrelling** [comment]
@echo-branch thats great to hear! Thanks for the hard work here and as well as all the communication on this thread. Really appreciate it!

**Comment by ragzy15** [comment]
@echo-branch It's great to hear it, thanks for all the hard work. 👍

**Comment by titooan** [comment]
Hi, 
I was looking for SPM support for the branch SDK, and I couldn't find anything in the documentation. Is it already released ? If yes, where can I find the documentation ? 

Thank you very much!

**Comment by echo-branch** [comment]
Shipped in https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/0.35.0
