### ISSUE TITLE
Error Building for Project Catalyst aka UIKit for Mac

### ISSUE THREAD

**Issue by EmperiorEric** [BranchMetrics/ios-branch-deep-linking-attribution#929]
Trying to build our iOS app with Project Catalyst and the Branch framework is failing to build with this error.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIWebView", referenced from:
      objc-class-ref in BNCDeviceInfo.o
      objc-class-ref in BranchViewHandler.o
ld: symbol(s) not found for architecture x86_64
```

I'm building with Xcode 11 Beta 5 and using Branch 27.1

**Comment by echo-branch** [comment]
We don't support macOS 15 via UIKit yet.  We have a backlogged ticket for this.

**Comment by kostassite** [comment]
Hello, Do you have any ETA for this issue? or any workaround?

**Comment by JoeySlomowitz** [comment]
Is there an update on this?  What is currently the recommend approach for using Branch in a catalyst app?

**Comment by echo-branch** [comment]
@JoeySlomowitz Unfortunately there are code level issues we need to resolve before we will work properly with Catalyst.  We have a ticket for this, however we haven't gotten it prioritized into a sprint yet.

**Comment by Patrick3131** [comment]
Hey @echo-branch was there any progress in implementing support for catalyst? Do you have any info when it will be available? Supporting Catalyst would be really useful.

**Comment by ccauquelin** [comment]
Hello @echo-branch, any news related to the support of Catalyst please?

**Comment by echo-branch** [comment]
@ccauquelin 
We're a bit short on dev resources at the moment, so this has fallen down the priority list. Can't give firm estimates until work for iOS 15 is done.

**Comment by echo-branch** [comment]
Recent versions of the iOS SDK should work with macCatalyst. We are still need to provide official documentation on this.

**Comment by hid-mpowell** [comment]
Thank you for letting us know as this will simplify our integration.

From: echo-branch ***@***.***>
Sent: Tuesday, May 9, 2023 10:09 PM
To: BranchMetrics/ios-branch-deep-linking-attribution ***@***.***>
Cc: Powell, Marc ***@***.***>; Manual ***@***.***>
Subject: [EXT] Re: [BranchMetrics/ios-branch-deep-linking-attribution] Error Building for Project Catalyst aka UIKit for Mac (#929)

CAUTION: This email is external. Do not click links or attachments that are unexpected or from unknown senders. If unsure, click the Report Phishing Button in Outlook.

Recent versions of the iOS SDK should work with macCatalyst. We are still need to provide official documentation on this.

-
