### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by voyage11** [BranchMetrics/ios-branch-deep-linking-attribution#931]
We identified one or more issues with a recent delivery for your app, APP_NAME. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

**Comment by radko93** [comment]
All `UIWebView` has to be replaced with `WKWebView`

**Comment by th3m477** [comment]
👍 needs to be fixed, only dependency i have with UIWebView's still.

**Comment by sjmueller** [comment]
👍 got this warning today, not a good situation if they require removal when iOS 13 is released!

**Comment by brunobar79** [comment]
+1

**Comment by radko93** [comment]
This will be fixed by #932

**Comment by priyankt** [comment]
+1

**Comment by h36ahmed** [comment]
+1

**Comment by alvarhansen** [comment]
+1

**Comment by jsiffels** [comment]
+1

**Comment by Budyn** [comment]
:+1:
