### ISSUE TITLE
Code signature is broken in simulator frame of release frameworks.

### ISSUE THREAD

**Issue by graysonlang** [BranchMetrics/ios-branch-deep-linking-attribution#934]
There is a bug with Xcode that it will automatically attempt to code sign simulator builds (i.e. architecture `x86_64`) unless you explicitly tell it not to. Since a valid certificate is not generally available at the time, it yields broken code signing and causes issues with framework stripping and resigning when a host application attempt to bundle/payload the framework during the final packaging process.

This can be seen by running the `codesign` tool from Apple to verify the binary:
```
$codesign --verify --deep --strict --verbose=2  Carthage/Build/iOS/Branch.framework/Branch
```

Which yields the error message:
```
Carthage/Build/iOS/Branch.framework/Branch: invalid Info.plist (plist or signature have been modified)
In architecture: x86_64
```

The expected result is:
```
Carthage/Build/iOS/Branch.framework/Branch: code object is not signed at all
```

The fix for this is to simply add the following to the project/target build settings:
```
CODE_SIGNING_ALLOWED = ""
```

**Comment by echo-branch** [comment]
There is a backlogged ticket for this issue.

**Comment by derrick-branch** [comment]
@graysonlang can you let us know if this is still an issue? I heard that Apple may have fixed this issue. Let us know; we're trying to clean up our backlog of github issues.

**Comment by echo-branch** [comment]
Moved to xcframework
