### ISSUE TITLE
Initialization of sdk with key (not in info.plist)

### ISSUE THREAD

**Issue by toddgower-hiatus** [BranchMetrics/ios-branch-deep-linking-attribution#937]
Is there a way to supply the Branch SDK with an API key rather than have it read from `info.plist`? I would like to keep the keys out of source control.

**Comment by echo-branch** [comment]
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/Branch-SDK/Branch.h#L176-L182

**Comment by toddgower-hiatus** [comment]
Yes, that's it! Why do the comments on that func say that this is not the preferred way of doing it? In my case, I'm going to be supplying the API key via codegen during the build process.

**Comment by echo-branch** [comment]
@toddgower-hiatus Not entirely sure to be honest.  It's historical and the current code base supports it.
