### ISSUE TITLE
Initialisation handler never called on iOS SDK 0.28.1 when checking for Apple Ads

### ISSUE THREAD

**Issue by ptsochantaris** [BranchMetrics/ios-branch-deep-linking-attribution#939]
After updating to the latest 0.28.1 Branch SDK (we were using 0.27.1) it seems that on some devices our app stopped launching. Digging deeper we found out that the completion handler for the initialisation call for Branch was never returning:

```
let branch = Branch.getInstance()
...
branch.delayInitToCheckForSearchAds()
branch.initSession(launchOptions: launchOptions, automaticallyDisplayDeepLinkController: true) { [weak self] params, error in
    // This is never called
}
```

It's important to note that this occurred only on certain devices, and when the SDK was run without breakpoints, indicating a race conditions. On some devices it never occurrs and on some device it always occurs. For instance, it's reproduced reliably on an iPhone 8 of a colleague.

Putting breakpoints in the SDK code we did a bit of digging that suggested that the failure was occurring when the code path was specific to when we had set the `branch.delayInitToCheckForSearchAds` call. And indeed, when removing that call, the SDK initialised and did the callback correctly.

Downgrading to 0.27.1 (thankfully before we shipped the latest version) fixes the issue reliably.

More than happy to provide any further info you may need to track this down.

**Comment by echo-branch** [comment]
There is a backlogged ticket for this.  On slow startup, we can enter a race condition.  The new SDK uses WebKit instead of UIWebView to obtain browser user agent on very first launch, which may take more time.

Workaround
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/Branch-SDK/Branch.h#L683

**Comment by ptsochantaris** [comment]
Hi, and thanks for the quick response. Would setting the `disableDelayedInit()` flag affect the search ads functionality, or other functionality of the SDK? What does this option normally do?

**Comment by echo-branch** [comment]
Potentially in very slow startups, we could miss the search ad data.  However, it's less severe than failing to call the callback for some users.  

Another thing to check for is a lot of setup prior to Branch setup.  That can also cause this issue.

Normally we wait for all the data on startup, however if we don't get it in time, this option tells the SDK to continue on.

**Comment by echo-branch** [comment]
0.29.0 should have a fix for this issue.

**Comment by ptsochantaris** [comment]
Hi, and thank you for the update! We'll upgrade the SDK in an upcoming version of our app 👍

**Comment by ptsochantaris** [comment]
We tried 0.29.0 but it seems to flood Xcode with warnings about null specifiers, as mentioned in #947 - we'll try again with the next version.

**Comment by echo-branch** [comment]
0.30.0 has a major update to search ads handling

**Comment by ptsochantaris** [comment]
This seems to still be happening with 0.29.3.

0.30.0 seems to have crashing issues right now from what we see in the issues list, so we're afraid to update to that. Will try again with 0.30.x hopefully. 🤞
