### ISSUE TITLE
BNCUserAgentCollector.h not found in BNCDeviceInfo.m

### ISSUE THREAD

**Issue by nick-sturrock** [BranchMetrics/ios-branch-deep-linking-attribution#940]
I get a flie not found building this module: BNCUserAgentCollector.h not found in BNCDeviceInfo.m. Any clues?

**Comment by echo-branch** [comment]
First guess is that there's some intermediate build artifacts floating around.  That file was added in 0.28.1

Could you try a full clean and rebuild?  

If that doesn't work, how did you integrate the SDK?  Cocoapods?  Carthage?

**Comment by nick-sturrock** [comment]
Integrated with Cocoapods, full clean results in the same issue. My pod installation of this module is definitely missing that header though...

**Comment by echo-branch** [comment]
Could you try remove the lock file and Pods folder and then doing a pod update?  I'm expecting the following file to exist.

 /Pods/Branch/Branch-SDK/Branch-SDK/BNCUserAgentCollector.h
