### ISSUE TITLE
Deep link doesn't work as expected when opened from in-app (iOS)

### ISSUE THREAD

**Issue by rishabh-latfire** [BranchMetrics/ios-branch-deep-linking-attribution#944]
Scenario 1 (Expected): 
1  App is in killed state or background
2  User clicks on link 
3 App opens and user is redirected to the desired page

Scenario 2 (Not Expected):
1. App is in foreground
2. Link is clicked from inside the app 
3. Safari browser opens asking to redirect to my app (I guess this is because Url scheme gets invoked here instead of universal link (just for this case))
4. Now if this link is clicked for the first time( after app launch) or no other link has been clicked before, the app opens but user is not redirected. The custom payload data is missing and instead I get `clicked_branch_link` as `false` and a new parameter `non_branch_link` ( Even though the link being used is a universal link). 
Note that if the same link is clicked again things start to work again as expected (Although still through a browser redirect). It works until another link is clicked in which case the scenario repeats itself.

Any help is appreciated. Also please note that unlike some related issues my `Branch.initSession()` does get called everytime.
I have not implemented cordovia plugin inside my app. Could that help?

**Comment by echo-branch** [comment]
There's a known race condition with slow initialization, such as search ads or initializing something large before Branch.  Working on a fix. 

Workaround
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/Branch-SDK/Branch.h#L683

**Comment by rishabh-latfire** [comment]
I tried using `disabledelayedinit` but the problem still persists. My code : 
 `// listener for Branch Deep Link data
		Branch.getInstance().disableDelayedInit()
		Branch.getInstance().initSession(launchOptions: launchOptions) { [weak self] _params, _ in

			guard let `self` = self else {
				return
			}

			// do stuff with deep link data (nav to page, display content, etc)
			guard let params = _params as? [String: AnyObject]
			else {
				return
			}`

**Comment by echo-branch** [comment]
0.29.0 has a fix for the race condition.  The workaround only works if the delay was due to search ads.

**Comment by echo-branch** [comment]
There's general init improvements in 0.30.0.

Note the SDK was aggressively trying to avoid init error conditions without saying anything.  This led to odd edge cases where callbacks are missed.  Now we log a message indicating we're avoiding an error.  Most often this is when there is a very long delay before initialization or an API that requires init was called before init.

**Comment by ahmadsallam** [comment]
same issues here

**Comment by astephensen** [comment]
Has anyone had any luck with this? I'd say about 70% of the time the `initSession` callback is called with `params` having a `+non_branch_link` parameter instead. Tried using `disableDelayedInit` with our current SDK version (0.25.5) and also tried updating to the latest (0.31.4) with no success.

Would also appreciate any tips in debugging this!

**Comment by echo-branch** [comment]
@astephensen 
Could you file a ticket with our support team?  They'll be able to spend more time with you on figuring out if this is a bug or configuration issue.  Thank you.
