### ISSUE TITLE
Crash on Archived app for 0.28.1

### ISSUE THREAD

**Issue by GLJeffery** [BranchMetrics/ios-branch-deep-linking-attribution#946]
I use Carthage for dependency management, and have been using 0.26.0, everything was fine.

I upgraded to 0.28.1 and everything runs in Xcode/simulator, but whenever I archive with this version, the app crashes immediately, has anyone else run into this issue?

**Edit**: Appears to be related to passing Branch instance through Fabric on device

*** Terminating app due to uncaught exception 'FABException', reason: '[Fabric] It appears that "Branch" is not a valid Fabric Kit. Please make sure you only pass Fabric Kits to [Fabric with:].'

**Comment by GLJeffery** [comment]
This happens on both Xcode 10.3 and Xcode 11 (not restricted to IDE)

**Comment by echo-branch** [comment]
I'm not able to repro this issue.  I double checked that the 0.29.0 framework has the necessary slices. 

`Branch: Mach-O universal binary with 4 architectures: [i386:Mach-O dynamically linked shared library i386] [arm64]
Branch (for architecture i386):	Mach-O dynamically linked shared library i386
Branch (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Branch (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Branch (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
`

At this point could you check if dropping in the old framework still works?  Just trying to narrow down the possibilities here.

**Comment by echo-branch** [comment]
Also just to be extra sure I understand the issue correctly.  You're talking about loading an ipa to device and seeing it crash immediately?  Also the app loaded to device via xcode works?

**Comment by GLJeffery** [comment]
I saw this issue on the 0.28.1 framework specifically, I haven't tried the 0.29.0 framework, and didn't try anything between 0.26.0 and 0.28.1

I had ended up reverting to the 0.26.0 for the time being.

Correct, loading via ipa (through Devices), or in Testflight, both crashed immediately, even though it archives. App loaded to simulator worked, I can do some tests tonight on app loaded to physical device on Xcode and let you know what happens.

Signing was my first thought too so I made new certs and profiles, but they weren't an issue in this case because using the same certs with 0.26.0 worked.

**Comment by echo-branch** [comment]
Could you check if WebKit is included?  It's now a requirement since Apple is giving warnings about future apps submissions with UIWebView will be rejected.  We use it to obtain browser user agent.

I think that's the biggest change in 0.28.x vs previous versions.

**Comment by GLJeffery** [comment]
it is, we use WKWebView directly in our app, as well as I was able to update other libraries which had the deprecation warning too without issue.

**Comment by GLJeffery** [comment]
App loaded to device via Xcode build worked, I will try archiving with 0.29.0 when I have the chance

**Comment by echo-branch** [comment]
Maybe the test device wasn't registered for running archives?

**Comment by GLJeffery** [comment]
same devices as normal

**Comment by GLJeffery** [comment]
@echo-branch did anything change regarding Branch.getInstance() and Fabric Kit?
after some more digging, I think this is the actual error I'm getting, not archive related:

** Terminating app due to uncaught exception 'FABException', reason: '[Fabric] It appears that "Branch" is not a valid Fabric Kit. Please make sure you only pass Fabric Kits to [Fabric with:].'

**Comment by echo-branch** [comment]
Ah yes.  Fabric is deprecated by Google and will be removed next Sprint.  We removed it in 0.28.1.

https://get.fabric.io/roadmap?utm_campaign=discover&utm_medium=natural

**Comment by GLJeffery** [comment]
Closing as this is an issue related to trying to pass Branch into Fabric which doesn't conform anymore, thanks for your help @echo-branch !
