### ISSUE TITLE
Branch.h: Pointer is missing a nullability type specifier

### ISSUE THREAD

**Issue by ileitch** [BranchMetrics/ios-branch-deep-linking-attribution#947]
Just upgraded to 0.29.0 from 0.27.1 and now I'm getting hundreds of errors concerning the lack of nullability specifiers in Branch.h.

The very first error is:
```
Pods/Headers/Public/Branch/Branch.h:72:17: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
```

Xcode 10.3
CocoaPods 1.7.5

**Comment by ileitch** [comment]
Looks to be a new issue in 0.29.0, I just tried 0.28.1 and it compiles without error.

**Comment by ileitch** [comment]
I'm still using Xcode 10.3.

**Comment by echo-branch** [comment]
I mean when I built the SDK in Xcode 11, it updated the warning settings.

**Comment by jervincruz** [comment]
Branch employee here: Currently have a client that's had the same error with 0.29 pod. Will this be fixed in the next release?

**Comment by kbelter** [comment]
i also have this problem.
Please let us know when this is fixed.
thanks!

**Comment by rdingman** [comment]
FYI, I've added `-Xcc -Wno-nullability-completeness` to "Other Swift Flags" in my project to suppress these warnings until this gets patched. Hope this helps someone.

**Comment by Ariandr** [comment]
Same issue. Waiting for solution! Thanks

**Comment by echo-branch** [comment]
A fix for this is in staging and being reviewed/tested.

**Comment by Ariandr** [comment]
@echo-branch Thanks for notice!

**Comment by Vinzius** [comment]
Hey Team,

The `Branch.getInstance()` property is now optional, is that the desired behavior? As any call will look like `Branch.getInstance()?.doSomething()`.

Thanks

**Comment by echo-branch** [comment]
@Vinzius 

Long ago we made the unfortunate choice to return nil in the event that Branch is misconfigured.  In a future release, I plan on hiding this and always making sure you get an object back.

**Comment by michalcichon** [comment]
I believe this issue should be closed as this issue is fixed in v0.29.1.

**Comment by macnibblet** [comment]
This is still an issue in 4.2.1?

**Comment by echo-branch** [comment]
@macnibblet Are you using React Native?  It hasn't been updated yet.

**Comment by macnibblet** [comment]
@echo-branch Makes sense, any chance we can see react native being upgraded since I cannot see build errors in gitlab-ci because the logs generated from these errors are so large gitlab cuts them off.

**Comment by mickeyjc** [comment]
We are using react native too, can you update the podspec in it and point it to a latest version.
There are thousand of nullability warning which breaks our CI logs, as it is cutting them off, and we can't scroll to the bottom of the logs.
