### ISSUE TITLE
Delay when try to share deep link.

### ISSUE THREAD

**Issue by SOleinichLohika** [BranchMetrics/ios-branch-deep-linking-attribution#948]
I have stange behaviour when try to generate and share deep link. If I create a deep link and share it using sdk throught iMessage, the app has delay about 10 seconds.

I create BranchUniversalObject:
```
let branchUniversalObject = BranchUniversalObject(canonicalIdentifier: "1111")
branchUniversalObject.contentDescription = "Test description"
branchUniversalObject.imageUrl = "https://deppzgntallyy.cloudfront.net/aHR0cHM6Ly9pbWFnZXMuZGV2Lmluc3BvbmV0d29yay5jb20vaW1hZ2VzL3N0b3JpZXMvMjYzL293T1lLa25NSS5qcGVn?signature=6fbc8bffdd1abf969a2da9bb1318861dd874808cb1d7210a5120aeac63db86c4&max=300"
branchUniversalObject.publiclyIndex = false
branchUniversalObject.locallyIndex = false
```

Then I create BranchLinkProperties
```
let linkProperty = BranchLinkProperties()
linkProperty.addControlParam("$fallback_url", withValue: "my.feedback.url")
```

Then I try to share:
```
branchUniversalObject.showShareSheet(
      with: linkProperty,
      andShareText: nil,
      from: viewController,
      completionWithError: nil
    )
```

Another way:
```
let shareLink = BranchShareLink(universalObject: branchUniversalObject, linkProperties: linkProperty)
    shareLink.presentActivityViewController(from: viewController, anchor: nil)
```

As the result my app has a delay:

![icon](https://media.giphy.com/media/dag585H6UwKOLgQFwf/giphy.gif)

If my app try to share not a deeplink then it works without delay.

**Comment by echo-branch** [comment]
@SOleinichLohika Sorry about the delay.  I didn't see this ticket.  

Could you email our support team?  I think this might be a configuration issue rather than a bug.

**Comment by dokutoshi** [comment]
I agree with @SOleinichLohika  @echo-branch - Issue occurs the first time on resume e.g the app was terminated by iOS and the user opens the app.

**Comment by echo-branch** [comment]
closing. Assuming reporter has a support ticket in.
