### ISSUE TITLE
Under iOS 13.1, showShareSheetWithLinkProperties places link before andShareText

### ISSUE THREAD

**Issue by lhasiuk** [BranchMetrics/ios-branch-deep-linking-attribution#952]
In iOS versions prior to 13, when using BranchUniversalObject's showShareSheetWithLinkProperties to send a link via Messages, the link appeared after any included text ("andShareText") parameter.  In iOS 13.1 (and possibly iOS 13), the link appears before the text in the text message.  This makes it difficult to make a message that explains to the user what the link is for, since it appears first and looks a bit strange as the opening of a text message.  The behavior was observed with library versions 0.25.6 (what we had been using) and the latest, 0.29.1

**Comment by echo-branch** [comment]
Logged a ticket for this issue.

**Comment by echo-branch** [comment]
@lhasiuk So I was able to previously repro this, however on iOS 13.2.2 it no longer repros.  Are you seeing the same behavior?

**Comment by echo-branch** [comment]
I believe Apple fixed this issue.  Please reopen if you encounter it on iOS 13.2.2+

**Comment by lhasiuk** [comment]
Sorry for not responding sooner.  It does appear to be fixed in 13.2.2.
