### ISSUE TITLE
0.29.3 - XCode 11 - 'BNCContentDiscoveryManager.m' in the Compile Sources build phase is using platform filters which is not supported in the legacy build system

### ISSUE THREAD

**Issue by loilee** [BranchMetrics/ios-branch-deep-linking-attribution#957]
Not sure if this is Xcode 11 issue but would like to show error when running carthage update in 0.29.3

Xcode 11
Carthage 0.34.0

*** Checking out ios-branch-deep-linking at "0.29.3"
carthage update error:

*** Building scheme "Branch iOS SDK Carthage" in TestBed-Swift.xcworkspace
Build Failed
	Task failed with exit code 65:

Log file:
=== BUILD TARGET Branch OF PROJECT BranchSDK WITH CONFIGURATION Release ===

Check dependencies
error: 'BNCContentDiscoveryManager.m' in the Compile Sources build phase is using platform filters which is not supported in the legacy build system.
error: 'BNCContentDiscoveryManager.m' in the Compile Sources build phase is using platform filters which is not supported in the legacy build system.
error: 'BNCThreads.h' in the Headers build phase is using platform filters which is not supported in the legacy build system.

** ARCHIVE FAILED **

**Comment by echo-branch** [comment]
This is a known issue.  I forgot to include it in the last patch, it's on staging now.

Basically, the swift project used for building the carthage binary requires new build system.

**Comment by loilee** [comment]
Got it. When can we expect it to be available?

**Comment by syedharishussain** [comment]
Also `BNCEncodingUtils.h`

**Comment by echo-branch** [comment]
@loilee By the end of next week.

**Comment by echo-branch** [comment]
@syedharishussain BNCEncodingUtils wasn't intended to be public.  The test project was inappropriately using private headers.  That should be fixed in the next release too.

**Comment by ashby-thornwell** [comment]
@echo-branch Do you happen to know when the next release will be available?

**Comment by echo-branch** [comment]
@ashby-thornwell probably mid next week.

**Comment by ashby-thornwell** [comment]
@echo-branch great, thanks!

**Comment by echo-branch** [comment]
This should be fixed in 0.30.0
