### ISSUE TITLE
Crash during initalisation.

### ISSUE THREAD

**Issue by bharathreddy-97** [BranchMetrics/ios-branch-deep-linking-attribution#964]
Following is my app delegate.
`
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        Branch.setUseTestBranchKey(true)
        Branch().initSession(launchOptions: launchOptions) { (params, error) in
            print("PARAMS   ",params,"\nError   ",error)
        }
        return true
    }
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        Branch.getInstance()?.application(app, open: url, options: options)
        return true
    }
`
But as soon as app is launched it is crashing.

<img width="903" alt="Screenshot 2019-11-06 at 12 37 15 PM" src="https://user-images.githubusercontent.com/15521339/68276490-1f16c580-0093-11ea-9960-e15135b77231.png">

**Comment by echo-branch** [comment]
Try replacing `Branch().initSession` with `Branch.getInstance()?.initSession`.

**Comment by bharathreddy-97** [comment]
@echo-branch  It worked..Thank you
