### ISSUE TITLE
Every time show error message when redeemRewards function call Swift

### ISSUE THREAD

**Issue by shamdass** [BranchMetrics/ios-branch-deep-linking-attribution#965]
Hello Team, 
I am developing an iPhone application with integrating Branch.io in which my client wants Referrals functionality. According to Referrals Documentation i've done almost all steps. when i m trying to load rewards and  redeem rewards then error message print: **You're trying to redeem more credits than are available. Have you loaded rewards?** Please Suggest me how to load rewards
Any other hand if you don't mind please share any project which already complete Referrals functionality. Because i'm confused how to complete this.

**Comment by echo-branch** [comment]
Please contact our support team for integration questions.  We generally only monitor github for bug reports.
