### ISSUE TITLE
Make Branch instance non-optional

### ISSUE THREAD

**Issue by willbattel** [BranchMetrics/ios-branch-deep-linking-attribution#966]
@echo-branch I saw you mention your intention to make the branch instance non-optional, as it was before version 0.29. I wanted to make this issue to publicly track that request so that we might more clearly know when that change is coming. Thanks!

> Long ago we made the unfortunate choice to return nil in the event that Branch is misconfigured.  In a future release, I plan on hiding this and always making sure you get an object back.

_Originally posted by @echo-branch in https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/947#issuecomment-539133045_

**Comment by echo-branch** [comment]
This should be in 0.30.0
