### ISSUE TITLE
How to create custom bucket name swift

### ISSUE THREAD

**Issue by shamdass** [BranchMetrics/ios-branch-deep-linking-attribution#968]
Hello Team,

I've  done referral link functionality which load and redeem points from bucket. I am confused because in which no one function to set different name of bucket or create different bucket. In Branch.io get points from different buckets method below: 
`Branch.getInstance()?.getCreditsForBucket("XYZ")`. Please suggest how to create or set different bucket name. 
Thank you.

**Comment by derrick-branch** [comment]
Hi @shamdass, we have deprecated our credits system and do not actively support it. If you write into support@branch.io they may be able to help. But please note that this is not supported functionality. Sorry for the inconvenience.
