### ISSUE TITLE
App crash on launch with SDK 0.30.0

### ISSUE THREAD

**Issue by skware** [BranchMetrics/ios-branch-deep-linking-attribution#973]
Hi,

Since the latest sdk update my app crash at startup for the following reason:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FBSDKAppLink fetchDeferredAppLink: must be invoked from main thread.'

This is called from branch.m line (927) checkFacebookAppLinks

It calls  FBSDKAppLinkUtility : fetchDeferredAppLink from a background thread which is not permitted (NSAssert([NSThread isMainThread], @"FBSDKAppLink fetchDeferredAppLink: must be invoked from main thread.");)

**Comment by echo-branch** [comment]
Fixed in 0.30.1

I failed to remove my mock and test with the real FB object. :(

**Comment by skware** [comment]
Thanks for your quick fix!
