### ISSUE TITLE
The problem with getShortUrl(with: linkProperties), instead of a short url the method returns a huge url with all data

### ISSUE THREAD

**Issue by Ariandr** [BranchMetrics/ios-branch-deep-linking-attribution#984]
Hello.
The issue is relevant on SDK versions 0.31.0-0.31.1.

During the first app run, the method `branchUniversalObject.getShortUrl(with: linkProperties)` returns a huge URL instead of a short one. During the second run the method returns a normal short url as with previous SDK versions. Example of the link (when it's huge):

<img width="174" alt="Screenshot at Dec 18 14-06-27" src="https://user-images.githubusercontent.com/13591333/71085260-c8c39900-219f-11ea-9c12-f4e9d064b78a.png">
 
As you understand, such a link isn't appropriate for sharing.
As a side issue, an incorrect image preview is shown in some messenger apps and from some apps you cannot use it as a correct deeplink due to many special characters it contains (for example from Slack).

**Comment by Ariandr** [comment]
For now, we have to stick to v.0.30.1, because some features of our app heavily rely on correct short urls which work as deeplinks which lead into some peaces of functionality.

Thanks in advance.

**Comment by echo-branch** [comment]
@Ariandr 
What you're seeing is our timeout behavior.  How soon after app launch are you generating the shortlink?

**Comment by Ariandr** [comment]
@echo-branch
We didn't test the exact time, but definitely after several minutes, maybe even 5. And after I share the first link(huge), the second and the third links are also huge. In our case only killing and launching the app again solved the issue.

**Comment by echo-branch** [comment]
@Ariandr 
I'm not able to reproduce the issue as described.  In my own testing, this only happened if I called generateShortlink soon after launch.  Calling the same API a few seconds later returned the short link.

Could you try again with the 0.30.2 and provide some redacted logs?  0.30.0 had a bug where logging an event early would block the network queue until app restart.

**Comment by Ariandr** [comment]
Hi @echo-branch 
We will try, but we had the same issue both using 0.31.0 and 0.31.1.
And only restart helped.

My point is that it doesn't happen with 0.30.x versions with the same iOS code. Is there a possibility that the fix in 0.31.1 doesn't work in some cases?

**Comment by Ariandr** [comment]
Hi @echo-branch 
Got some logs for you (when it's the first session after installation). They are the same for iOS 12 and 13, tested on both.

[branch.io] Branch.m(185) Log: Branch version 0.31.2 started at 2019-12-24 10:03:26 +0000.

[branch.io] BNCServerInterface.m(827) Debug: URL: https://api2.branch.io/v1/install.

[branch.io] BNCServerInterface.m(831) Debug: Body: {
    ....
    ....
    .... // here everything is correct
}
[branch.io] BNCNetworkService.m(232) Debug: Network start operation https://api2.branch.io/v1/install.

[branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api2.branch.io/v1/install 0.400s. Status 200 error (null).

[branch.io] BNCServerInterface.m(887) Debug: Server returned: Status: 200; Data: {
    data = "{\"+clicked_branch_link\":false,\"+is_first_session\":true}";
    "device_fingerprint_id" = xxxxxxxxxxxxxx;
    "identity_id" = xxxxxxxxxxxxx;
    link = "xxxxxxxxx?%24identity_id=xxxxxxx";
    "session_id" = xxxxxxxxx;
}.

[branch.io] BNCNetworkService.m(232) Debug: Network start operation https://cdn.branch.io/sdk/uriskiplist_v0.json.

[branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://cdn.branch.io/sdk/uriskiplist_v0.json 0.222s. Status 200 error (null).
{"version":1, "uri_skip_list":["^fb\\d+:","^li\\d+:","^pdk\\d+:","^twitterkit-.*:","^com\\.googleusercontent\\.apps\\.\\d+-.*:\\\/oauth", "^(?i).+:.*[?].*\\b(password|o?auth|o?auth.?token|access|access.?token)\\b"]}.

[branch.io] BNCServerInterface.m(827) Debug: URL: https://api2.branch.io/v1/close.

[branch.io] BNCServerInterface.m(831) Debug: Body: {
    ....
    ....
    .... // here all fields
}

[branch.io] BNCNetworkService.m(232) Debug: Network start operation https://api2.branch.io/v1/close.

[branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api2.branch.io/v1/close 0.386s. Status 200 error (null).

[branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api2.branch.io/v1/close 0.386s. Status 200 error (null).
{}.

[branch.io] BNCServerInterface.m(887) Debug: Server returned: Status: 200; Data: {
}.

 **// It's last [branch.io] log, then I get short URL and it's a huge one instead of a short one.**

**Comment by Ariandr** [comment]
@echo-branch 
After the relaunch of the app, I get other logs. And also, which is more important, get logs when I try to get short url.

....
....
....

// Here I try to get a short url and it works properly

[branch.io] Branch.m(1662) Debug: Creating a custom URL synchronously.

[branch.io] BNCServerInterface.m(827) Debug: URL: https://api2.branch.io/v1/url.

[branch.io] BNCServerInterface.m(831) Debug: Body: {
...
...
...
}

[branch.io] BNCNetworkService.m(232) Debug: Network start operation https://api2.branch.io/v1/url.

[branch.io] BNCNetworkService.m(227) Debug: Network finish operation https://api2.branch.io/v1/url 0.246s. Status 200 error (null).
{"url":"xxxxxxxxxxxx","spotlight_identifier":"xxxxxxxxxxx"}.

[branch.io] BNCServerInterface.m(887) Debug: Server returned: Status: 200; Data: {
    "spotlight_identifier" = "xxxxxxxxxx";
    url = "xxxxxxxxxxx";
}.

**Comment by echo-branch** [comment]
Thanks for the logs!  I just got back from holiday and will take a look at this.

**Comment by echo-branch** [comment]
@Ariandr 
I was able to repro it, there was an app background foreground I was missing.  Working on a fix.

**Comment by Ariandr** [comment]
@echo-branch 
Great news, thank you!

**Comment by echo-branch** [comment]
@Ariandr 
Pushed out a fix for this.

**Comment by Ariandr** [comment]
@echo-branch 
Thank you!
It's pushed in v.0.31.3, right?

**Comment by Ariandr** [comment]
We tried a new version, the issue seems fixed, thanks!

**Comment by hoangtuanfithou** [comment]
@echo-branch : we got same issue with  `pod 'Branch', '0.31.1'` yesterday Jun 25. Sometime got long link, sometime get short link. It is more stable when we upgrade to pod 'Branch', '0.34.0'. But still happens sometime.

**Comment by hoangtuanfithou** [comment]
> this only happened if I called generateShortlink soon after launch. Calling the same API a few seconds later returned the short link.
@echo-branch : 
we still got this issue with `0.34.0`.
we have the screen that is deeplink to open after launch, and shortlink is generated on this screen.
issue happen always if simulate slow network (edge/3G).

**Comment by levantAJ** [comment]
Hi @echo-branch We still able to reproduce this issue on **0.34.0** Could you help with the investigation? Thanks

**Comment by echo-branch** [comment]
There's a feature ticket to make a version that returns an error instead of falling back to a long link automatically.  It might be a while until we get it done while addressing iOS 14 items.

**Comment by VuongTranCong** [comment]
Hi, @echo-branch May we follow up with you on when the issue will be fixed? We still face this issue, now

**Comment by frowing** [comment]
Same thing here, we're still seeing this issue. Any ideas @echo-branch?

**Comment by krati-nickelfox** [comment]
@echo-branch does it link to https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1029 ?
