### ISSUE TITLE
InitSession callback: Server returned: Status: 400 

### ISSUE THREAD

**Issue by andrijamilovanovic** [BranchMetrics/ios-branch-deep-linking-attribution#986]
HI,

From debug log, I got error:
   error =     {
        "cpu_type" = "wrong field type";
    };

Here is a package that was sent from my phone during startup:
`{"apple_testflight":true,"os_version":"13.2","ios_bundle_id":"REMOVED,"debug":true,"screen_dpi":2,"country":"RS","is_hardware_id_real":true,"locale":"en_RS","ad_tracking_enabled":true,"sdk":"ios0.31.1","uri_scheme":"REMOVED","environment":"FULL_APP","connection_type":"wifi","retryNumber":0,"facebook_app_link_checked":false,"lastest_update_time":1576719349000,"local_ip":"10.152.16.39","brand":"Apple","update":0,"cpu_type":16777228,"screen_height":1334,"apple_ad_attribution_checked":false,"model":"iPhone8,1","branch_key":"key_live_pkMImYyUWyhbBuMmtozd1iedFBcKrnkd","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148","first_install_time":1576714160417,"hardware_id":"90E54384-6DBD-4CC6-AC94-D77ECF66B6A5","os":"iOS","hardware_id_type":"vendor_id","latest_install_time":1576719366525,"screen_width":750,"build":"17B84","language":"en","ios_vendor_id":"90E54384-6DBD-4CC6-AC94-D77ECF66B6A5","app_version":"1.0.17","device_carrier":"mt:s"}`

I redacted application related details.

**Comment by echo-branch** [comment]
Just hotfixed this.

**Comment by alexcosmin** [comment]
Thank you for the fix @echo-branch !

Out of curiosity, I have a question. Yesterday, when I tested my implementation with version 0.31.1 of the iOS SDK everything worked fine. This morning no luck, due to this 'breaking server side change'. If I would have released to AppStore with 0.31.1, now I would have needed to make another release, to update the Branch SDK. Isn't it a better idea to fix these kind of issues on the server side, since that's where the issue occurred? This way everyone using 0.31.1 and 0.31.0 wouldn't need to make new releases, just to fix this?

**Comment by tmlshapr** [comment]
Not sure if it is the same issue, but with 0.31.2 I'm still getting these logs when sending in events:

```
[branch.io] BNCServerInterface.m(649) Error: An error prevented request to https://api2.branch.io/v2/event/custom from completing: Error Domain=io.branch.sdk.error Code=1003 "The network request was invalid." UserInfo={NSLocalizedDescription=The network request was invalid., NSLocalizedFailureReason=The request was invalid.}
```

**Comment by echo-branch** [comment]
@alexcosmin 
I totally agree.  The estimated time to fix on the server side was longer than putting out a fix on the client.  So we decided to do that asap.

**Comment by echo-branch** [comment]
@tmlshapr 
Could you provide a sample event?  I'm not seeing the same behavior in my test suite.

**Comment by andrijamilovanovic** [comment]
Just to confirm that everything works for in new version. 
Also, I had very similar network error as @tmlshapr reported in the previous version. I don't have it now, but it looks like these two are not related. 

Thanks.

**Comment by echo-branch** [comment]
@alexcosmin Just to update we're also rolling back the change on the server.
