### ISSUE TITLE
No documentation for deeplinking on iOS 13 with Scene Delegate

### ISSUE THREAD

**Issue by leojkwan** [BranchMetrics/ios-branch-deep-linking-attribution#989]
Prior to iOS 13, cold and warm app launches from app links would provide attribution parameters in the Branch init session callback:
```
Branch.getInstance().initSession(launchOptions: launchOptions) { [weak self] params, error in
      guard let parameters = params as? [String: Any] else {
        return
      }

      // Handle deep link
    }
```

When apps adopt Scene Delegates on iOS 13, cold start app launches no longer provide user activity contexts in the above callback.

Users must add the following check in SceneDelegate delegate method scene:willConnectTo:options.

```

  func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    guard let windowScene = (scene as? UIWindowScene)else {
      return
    }

    window = UIWindow(frame: windowScene.coordinateSpace.bounds)
    window!.backgroundColor = UIColor.primaryBlack
    window?.windowScene = windowScene

    // app-specific code
    
   // branch app link code
    if let userActivity = connectionOptions.userActivities.first {
      Branch.getInstance().continue(userActivity)
    }
  }
```

Where is the best place to add this Swift documentation?

**Comment by echo-branch** [comment]
@leojkwan 
Thanks for pointing out the readme docs haven't been updated for the newer scene delegate.

You can put the branch continueUserActivity call in the scene delegates continueUserActivity method, instead of the appDelegate continueUserActivity.  Which is a bit simpler.

**Comment by leojkwan** [comment]
@echo-branch thanks for responding. For some reason the scene delegates continueUserActivity is not called for me, (version 0.31.3) for app link opens on _cold_ app launches. `willConnectToSession` does get called though. Am I possibly missing something?

**Comment by echo-branch** [comment]
Interesting.  I'll see if I can repro why the continueUserActivity approach doesn't work for you.

**Comment by leojkwan** [comment]
thanks @echo-branch

**Comment by sjmueller** [comment]
@leojkwan THANK YOU for sharing your fix for this problem 🙏We spent a ridiculous amount of hours trying to track down cold start deep linking failures in our iOS 13 app, you saved us!

Going back we've now realized that tracking for other features has been subtly broken for months, I really can't believe branch has let this slip for so long without giving proper iOS 13 guidance or updating their docs.

**Comment by echo-branch** [comment]
Sorry about that.  I totally dropped the ball on putting in a docs update ticket for this Scenedelegate bug.  Getting it prioritized now.

**Comment by leojkwan** [comment]
Thanks @echo-branch
