### ISSUE TITLE
project using Branch pod fails to build with error library not found for -lBranch

### ISSUE THREAD

**Issue by jacobleesinger** [BranchMetrics/ios-branch-deep-linking-attribution#991]
Hi,

All of my projects using the Branch pod are failing to build with the error `library not found for -lBranch`

You can find a minimal project that reproduces the issue here: https://github.com/jacobleesinger/BareBonesBranchPod

Full error message from the above project: 

Ld /Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Products/Debug-iphonesimulator/BareBonesBranchPod.app/BareBonesBranchPod normal x86_64 (in target 'BareBonesBranchPod' from project 'BareBonesBranchPod')
    cd /Users/jacobsinger/workspaces/practice/BareBonesBranchPod
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios13.2-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -L/Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Products/Debug-iphonesimulator -L/Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Products/Debug-iphonesimulator/Branch -F/Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Products/Debug-iphonesimulator -filelist /Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Intermediates.noindex/BareBonesBranchPod.build/Debug-iphonesimulator/BareBonesBranchPod.build/Objects-normal/x86_64/BareBonesBranchPod.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Intermediates.noindex/BareBonesBranchPod.build/Debug-iphonesimulator/BareBonesBranchPod.build/Objects-normal/x86_64/BareBonesBranchPod_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lBranch -framework AdSupport -framework CoreTelephony -framework MobileCoreServices -framework SystemConfiguration -framework WebKit -framework iAd -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Intermediates.noindex/BareBonesBranchPod.build/Debug-iphonesimulator/BareBonesBranchPod.build/BareBonesBranchPod.app-Simulated.xcent -lPods-BareBonesBranchPod -Xlinker -dependency_info -Xlinker /Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Intermediates.noindex/BareBonesBranchPod.build/Debug-iphonesimulator/BareBonesBranchPod.build/Objects-normal/x86_64/BareBonesBranchPod_dependency_info.dat -o /Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Products/Debug-iphonesimulator/BareBonesBranchPod.app/BareBonesBranchPod

ld: warning: directory not found for option '-L/Users/jacobsinger/Library/Developer/Xcode/DerivedData/BareBonesBranchPod-hcwoktysvtuvkibotafjdyvgzckj/Build/Products/Debug-iphonesimulator/Branch'
ld: library not found for -lBranch
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by echo-branch** [comment]
I was unable to repro the issue using your project. Did you inadvertently open the project instead of the workspace?

**Comment by echo-branch** [comment]
closing as no response from reporter.
