### ISSUE TITLE
deeplinking url shared by facebook can't let me get the right data

### ISSUE THREAD

**Issue by chunyili200556** [BranchMetrics/ios-branch-deep-linking-attribution#992]
Hello Branch.io team ,it's me again.
Recently deeplinking url  have a problem that I can open my app by the url on facebook post but the dictionary I got from initSession is not correct. 
It cause we can't open the page we want. But the fun part is not every url on the facebook have this issue.
Only facebook have this problem. Line ,Email and other platform are working fine.

Please helping me for this problem. thanks~

**Comment by echo-branch** [comment]
FB adds additional parameters to the end of the shared URL that has caused a similar issue before.  We'll need a sample URL from you to debug this.  

Mind sending that information in a ticket to our support team?  Thank you.

**Comment by echo-branch** [comment]
closing.  Assuming reporter has a support ticket in.
