### ISSUE TITLE
App crash on initialization Release 0.31.3

### ISSUE THREAD

**Issue by shraddha009** [BranchMetrics/ios-branch-deep-linking-attribution#994]
dyld: Library not loaded: @rpath/Branch.framework/Branch
  Referenced from: /var/containers/Bundle/Application/10C3936E-8E2A-4BE3-8EA8-1A86C4A5B774/Iper.app/Iper
  Reason: image not found

**Comment by echo-branch** [comment]
@shraddha009 
Are you using cocoapods?  And if so, did you inadvertently open the project instead of the workspace?

**Comment by echo-branch** [comment]
closing as no response from reporter.
