### ISSUE TITLE
MobileCoreservices deprecation warnings in Xcode 11.4

### ISSUE THREAD

**Issue by alex-vasenin** [BranchMetrics/ios-branch-deep-linking-attribution#999]
Branch SDK installed with `pod Branch` produces the following warnings in Xcode 11.4 beta despite `inhibit_all_warnings!` in Podfile:

> Branch
> Target Integrity
> MobileCoreServices has been renamed. Use CoreServices instead.

It looks like there is no way to turn them off which is very annoying for those who stick to zero-warnings policy. Please fix!

**Comment by echo-branch** [comment]
Thanks for the heads up.  Backlogged a ticket to see if we can fix this while maintaining support for older Xcode versions.

**Comment by echo-branch** [comment]
This should be fixed in 0.34.0
